### ISSUE TITLE
Does MetONTIIME perform demultiplex?

### ISSUE THREAD

**Issue by tjlim10** [MaestSi/MetONTIIME#106]
Hi Simone,

May I know if MetONTIIME performs demultiplex on the sequence reads? If yes, which step is demultiplex conducted specifically?

Thank you!

Kind regards,
Timothy

**Comment by MaestSi** [comment]
Hi,
no, MetONTIIME does not perform demultiplexing. It may only concatenate reads fron multiple files into a single file for each barcode.
Best,
SM
