### ISSUE TITLE
Assign Taxonomy Error Unclear

### ISSUE THREAD

**Issue by irc47** [MaestSi/MetONTIIME#107]
Hi Simone, 
Can you help me understand this error? I'm not able to find in it any indication of what might have gone wrong. It is a failure of assignTaxonomy and occurs after a great deal of time has elapsed so seems to be something later on in the taxonomy task. 

executor >  local (1)
[bd/84419f] importDb (1)          | 1 of 1, cached: 1 ?
[c3/fc5509] concatenateFastq      | 1 of 1, cached: 1 ?
[d5/69d73a] filterFastq           | 1 of 1, cached: 1 ?
[2b/01d8d1] downsampleFastq       | 1 of 1, cached: 1 ?
[3b/59f0b3] importFastq           | 1 of 1, cached: 1 ?
[f0/c9b0b4] derepSeq              | 1 of 1, cached: 1 ?
[06/bf1206] assignTaxonomy (1)    | 1 of 1, failed: 1 ?
[-        ] filterTaxa            -
[-        ] taxonomyVisualization -
[-        ] collapseTables        -
[e1/24a426] dataQC                | 1 of 1, cached: 1 ?
[-        ] diversityAnalyses     -
ERROR ~ Error executing process > 'assignTaxonomy (1)'

Caused by:
  Process `assignTaxonomy (1)` terminated with an error exit status (137)

Command executed:

  mkdir -p /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/assignTaxonomy
  
  	classifier_uc=$(awk '{print toupper($0)'} <<< Vsearch)
  
  .commaif [ "$classifier_uc" == "BLAST" ]; then
  ery /home/exouqiime feature-classifier makeblastdb e_greengenes_august--i-sequences /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/importDb/2022.10.backbone.full-length.fna.qza .backbone.full-leng--o-database /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/importDb/blastIndexedDb.qza
  
  ts 3 --p-min-cqiime feature-classifier classify-consensus-blast bel 'Unassigned' --p-t--i-query /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/derepSeq/rep-seqs.qza  nTaxonomy/taxonom--i-blastdb /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/importDb/blastIndexedDb.qza search_results.--i-reference-taxonomy /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/importDb/2022.10.backbone.tax.qza 			--p-num-threads 6 			--p-perc-identity 0.9 			--p-query-cov 0.8 			--p-maxaccepts 3 			--p-min-consensus 0.7 		--o-classification /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/assignTaxonomy/taxonomy.qza 			--o-search-results /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/assignTaxonomy/search_results.qza
  nd linelif [ "$classifier_uc" == "VSEARCH" ]; then
  		qiime feature-classifier classify-consensus-vsearch 			--i-query /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/derepSeq/rep-seqs.qza  			--i-reference-reads /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/importDb/2022.10.backbone.full-length.fna.qza 			--i-reference-taxonomy /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/importDb/2022.10.backbone.tax.qza 			--p-perc-identity 0.9 			--p-query-cov 0.8 			--p-maxaccepts 100 			--p-maxrejects 100 			--p-maxhits 3 			--p-min-consensus 0.7 			--p-strand 'both' 			--p-unassignable-label 'Unassigned' 			--p-threads 6 			--o-classification /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/assignTaxonomy/taxonomy.qza 			--o-search-results /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/assignTaxonomy/search_results.qza
  	else
  		echo "Classifier Vsearch is not supported (choose between Blast and Vsearch)"
  	fi
  
  qiime metadata tabulate 		--m-input-file /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/assignTaxonomy/taxonomy.qza 		--o-visualization /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/assignTaxonomy/taxonomy.qzv
  
  	qiime taxa filter-table 		--i-table /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/derepSeq/table.qza 		--i-taxonomy /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/assignTaxonomy/taxonomy.qza 		--p-exclude Unassigned 		--o-filtered-table /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/derepSeq/table-no-Unassigned.qza

Command exit status:
  137

Command output:
  (empty)

Command error:
  .command.sh: line 14:    10 Killed                  qiime feature-classifier classify-consensus-vsearch --i-query /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/derepSeq/rep-seqs.qza --i-reference-reads /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/importDb/2022.10.backbone.full-length.fna.qza --i-reference-taxonomy /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/importDb/2022.10.backbone.tax.qza --p-perc-identity 0.9 --p-query-cov 0.8 --p-maxaccepts 100 --p-maxrejects 100 --p-maxhits 3 --p-min-consensus 0.7 --p-strand 'both' --p-unassignable-label 'Unassigned' --p-threads 6 --o-classification /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/assignTaxonomy/taxonomy.qza --o-search-results /home/exouser/MetONTIIME/NP24/results_metontiime_greengenes_august6/assignTaxonomy/search_results.qza

Work dir:
  /home/exouser/MetONTIIME/work/06/bf120609eaa5caa9f839a9068e2f15

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

**Comment by MaestSi** [comment]
Hi,
I think this is a RAM memory error, similar to [this one](https://github.com/MaestSi/MetONTIIME/issues/83#issue-2067117076).
See that issue for proposed solutions.
SM

**Comment by MaestSi** [comment]
Closing this one, as conversation continued in the related issue.
Best,
SM
