### ISSUE TITLE
Looking for a pre-taxonomic assignment OTU table

### ISSUE THREAD

**Issue by irc47** [MaestSi/MetONTIIME#108]
Hello,
I want to have an OTU table in which OTUs are identified by feature id and/or consensus sequence instead of by an assigned taxonomy (so that I can do phylogenetic analysis that isn't database dependent). Do you have any suggestions for how to get to this? It seems that something like it must exist at some point in the MetONTIIME process, because isn't this information used in the unifrac diversity analysis? But it doesn't seem to be an output and I haven't figured out how to reverse-engineer it. Does this make sense? Am I missing something in the outputs or could you suggest an approach for this? 
--Ilana

**Comment by MaestSi** [comment]
Hi,
I think what you are referring to is the ${params.resultsDir}/derepSeq/rep-seqs.qza file. You can tune **clusteringIdentity** parameter to change the minimum alignment identity within each cluster (= OTU).
For example, QIIME2 can use rep-seqs.qza file to evaluate phylogenetic diversity metrics, with code similar to the following.

```
qiime phylogeny align-to-tree-mafft-fasttree \
  --i-sequences rep-seqs.qza \
  --o-alignment aligned-rep-seqs.qza \
  --o-masked-alignment masked-aligned-rep-seqs.qza \
  --o-tree unrooted-tree.qza \
  --o-rooted-tree rooted-tree.qza

qiime diversity core-metrics-phylogenetic \
  --i-phylogeny rooted-tree.qza \
  --i-table table.qza \
  --p-sampling-depth $SAMPLING_DEPTH \
  --m-metadata-file sample-metadata.tsv \
  --output-dir core-metrics-results
```

Best,
SM

**Comment by MaestSi** [comment]
Close due to inactivity. Feel free to reopen it, in case you have any further issues.
Best,
SM

**Comment by hpeter0803** [comment]
Hi, I am looking for the same - a feature table, with absolute or relative counts of features in the different samples. Thanks for your help! Hannes

**Comment by MaestSi** [comment]
Hi @hpeter0803, please refer to the previous comment, and, in case you have any issues, please let me know.
SM
