### ISSUE TITLE
metONTIIME Running Slow  - Cannot Increase RAM

### ISSUE THREAD

**Issue by danuccio** [MaestSi/MetONTIIME#109]
I have set metONTIIME to use 200 GB of RAM on a device with ~250GB for the more RAM intensive steps (e.g. taxonomic assignment). 

```
withName:assignTaxonomy{
			container = 'maestsi/metontiime:latest'
			cpus = { params.assignTaxonomy ? 6 : 1 }
			memory = { params.assignTaxonomy ? 200.GB + (2.GB * (task.attempt-1)) : 1.GB }
			errorStrategy = { task.exitStatus == 130 ? 'retry' : 'terminate' }
			maxRetries = 3
```

However, whenever I check htop, metONTIIME never seems to be using more than ~6-20GB or RAM.

At present, my current run has been going on for nearly one month. It has been performing the taxonomic assignment step for the past three weeks.

While troubleshooting an earlier step, I reached out to one of the developers on this page about increasing CPUs in addition to memory, but was advised against doing so. 

https://github.com/MaestSi/MetONTIIME/issues/100

Based on the parameters I included above, can you tell if I have this set up properly?

Do you have any additional recommendations?

Thank you

**Comment by MaestSi** [comment]
Hi, in the previous issue you raised, the program crashed due to unavailable RAM memory. In this run, it seems it is not crashing (at least, up to now), but of course it is taking a long time. I think it's a matter of finding the right compromise between number of threads (the higher the faster the process will be, but also it will require more memory) and consumed memory (here you have a hard limit, which may the process crash). My advice would be to set **downsampleFastq** process to true (if it is not already set) and to set a lower **maxNumReads**, a few tens of thousands per sample should be ok, but I don't know how many samples you are analysing. If you have many samples, you should consider splitting them in groups, analysing each group separately and then merging feature tables afterwards. Please also check that you are editing the portion of the config file related to the profile (i.e. docker or singularity) you are using.
Best,
SM

**Comment by arrow00** [comment]
Hello,
@danuccio , did You have any progress with Your analyses?
I also have similar problems with dataset consisted of 25 samples with downsampleFastq set to 50k per sample.
metONTIIME stucked at assignTaxonomy for the last seven days and when I check CPU and RAM usage it does nothing.
I found and error when checked log:
 `Oct-19 21:32:18.372 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 8; name: assignTaxonomy (1); status: RUNNING; exit: -; error: -;`
which shows every five minutes.
However, I do not know whether this error is important as it was also present in my test run (with lower number of samples) and test run finished without any problems.

@MaestSi, do You have any information of how long it takes (more or less of course) to analyse datasets You analysed as I do not know whether I should start to worry or just wait more.

Thank You all for support.

All the best,

Tomek

**Comment by MaestSi** [comment]
I think it should be possible to identify the temporary file where taxonomy results are being written with htop. Then, it should be possible to grep for some string in the tmp file and run wc -l to estimate the number of reads already processed. In any case, I never analysed more than a few hundred thousands reads per run. If you have more, I suggest to split the dataset in chunks (e.g. a group of samples for each chunk) and run the pipeline for each chunk. Later on, you can merge the resulting tables with simple QIIME2 commands.
SM

**Comment by arrow00** [comment]
Thank You for lightning speed response :)

> I think it should be possible to identify the temporary file where taxonomy results are being written with htop.

Htop is showing dozens of docker processes which do not use CPU or RAM and write files to work directory:
![Zrzut ekranu 2024-10-19 223519](https://github.com/user-attachments/assets/9452fc32-090d-4094-ba86-921bdede16dd)

but apart from command.* files there is nothing in there.

There are also six active (using 100% CPU per process) blastn processes which write data to some tmp directory (/tmp/q2-BLAST6FORMAT-lu6sv1l0):
![Zrzut ekranu 2024-10-19 223903](https://github.com/user-attachments/assets/653df624-1c9a-4f8e-92da-db1773e808c1)

but I think (I do not know whether I am right) that as those files are within docker machine, I have to look it there (they will not be directly visible on my disk - I have to connect to dockers shell with something like
```
docker exec - it <container-name> /bin/bash
``` 
and check it there ).

I will check it and let You know whether I will be able to find them.



> If you have more, I suggest to split the dataset in chunks (e.g. a group of samples for each chunk) and run the pipeline for each chunk. Later on, you can merge the resulting tables with simple QIIME2 commands.

As for the splitting. What do You mean by chunks? Should I in my case split those 25 samples into groups of let's say 5 samples with all reads and analyze them separately five times. Or maybe analyse them together (25 at once) just downgrade number of reads per sample to let's say 5k and analyze them ten times?

Once more thank You for support.

Greetings,

Tomek

**Comment by MaestSi** [comment]
I was mainly thinking of analysing a set of samples at once (all reads from a subset of samples)
SM

**Comment by danuccio** [comment]
@arrow00  I opted to give metONTIIME a little more time. Then it crashed. I have not restarted it yet.

@MaestSi It looks prior to getting stuck on the taxonomic assignment step, metONTIIME did successfully create a rep-seqs.qza file and a table.qza file. Would it be possible to just import these into QIIME2 and complete the taxonomic assignment step there?

Thank you

**Comment by MaestSi** [comment]
Hi @danuccio , yes, it is possible to import them into QIIME2 and proceed outside of the pipeline. However, I don't think this will make any differences compared to restarting the pipeline from the **assignTaxonomy** process with `-resume`.

@arrow00: I am not 100% sure those tmp directories will be inside the docker container and not accessible from the outside, but you may be right. In any case, based on the processes you showed, it looks like you are using Blastn classifier. Vsearch is usually much faster, so you may consider using that one instead.

**Comment by arrow00** [comment]
> @arrow00: I am not 100% sure those tmp directories will be inside the docker container and not accessible from the outside, but you may be right. In any case, based on the processes you showed, it looks like you are using Blastn classifier. Vsearch is usually much faster, so you may consider using that one instead.

I checked and indeed it is inside docker container. As for the blast efficiency, I have 1 136 052 reads in total to analyze and up to now blast checked 220 366 of them which took ~six days.

In my opinion and in line with Your suggestion this is slow so I stopped analyses, changed blast to vsearch and resumed it after it.
Now it is much better as after 20 min more than 50k reads was analysed.

I will keep You informed how it is going.

Once more thank You for support.

Tomek

**Comment by MaestSi** [comment]
Feel free to add any comments here. Closing the issue.
Best,
SM
