### ISSUE TITLE
How to find differences between the communities in bar graph?

### ISSUE THREAD

**Issue by sekhwal** [MaestSi/MetONTIIME#11]
Hi, 
I have got a question. Could you please suggest any method to quantify the extent of differences between the three (BC08, BC09 and BC10) communities.

Can Chi square test tell us whether the different community compositions are likely drawn from the same distribution of genera?

**Comment by MaestSi** [comment]
Hi,
personally I would think about some alpha and beta diversity metrics, but unfortunately I am not expert about that. Maybe you could ask it in QIIME2 forum and see what they suggest.
Simone

**Comment by sekhwal** [comment]
Ok! Thanks.
