### ISSUE TITLE
Problem with finding the path 'workDir'

### ISSUE THREAD

**Issue by sebastianavalon** [MaestSi/MetONTIIME#110]
Hi.
I have a problem with the path to the fastq.gz files apparently not existing. Of course it is created and fastq.gz has 'barcode' in its name. I run Metontiime from WSL (ubuntu). I did not make any key changes in the .conf and .nf files, I only gave the paths to the folder with the *fastq.gz (workdir) and resultsdir files to check if the beginning of processing starts.
And here the problem appears, because nextflow does not find the given paths with files (or 1 file). Experience with pipelines is new to me and I am just starting my adventure with this matter.

```nextflow

``` /mnt/c/Users/avalo/metontiime$ nextflow -c metontiime2.conf run metontiime2.nf --workDir="/home/avalo/metontiime/diana" --resultsDir="/home/avalo/metontiime/results" -profile docker

 N E X T F L O W   ~  version 24.04.4

Launching `metontiime2.nf` [big_kimura] DSL2 - revision: cadfc622f6

executor >  local (2)
executor >  local (2)
[-        ] process > importDb (1)          -
[0d/536bd3] process > concatenateFastq      [100%] 1 of 1, failed: 1 ✘
[-        ] process > filterFastq           -
[-        ] process > downsampleFastq       -
[-        ] process > importFastq           -
[-        ] process > derepSeq              -
[-        ] process > assignTaxonomy        -
[-        ] process > filterTaxa            -
[-        ] process > taxonomyVisualization -
[-        ] process > collapseTables        -
[-        ] process > dataQC                -
[-        ] process > diversityAnalyses     -
ERROR ~ Error executing process > 'concatenateFastq'

Caused by:
  Process `concatenateFastq` terminated with an error exit status (1)


Command executed:

  mkdir -p /home/avalo/metontiime/results
  mkdir -p /home/avalo/metontiime/results/concatenateFastq
  cp /home/avalo/metontiime/diana/*fastq.gz /home/avalo/metontiime/results/concatenateFastq

Command exit status:
  1

Command output:
  (empty)

Command error:
  cp: cannot stat '/home/avalo/metontiime/diana/*fastq.gz': No such file or directory

Work dir:
  /mnt/c/Users/avalo/metontiime/work/0d/536bd3e53e6285e5fa7cf48db44918

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

**Comment by MaestSi** [comment]
Hi, I hope this solved the issue. In case it didn't, feel free to reopen it.
Best,
SM

**Comment by sebastianavalon** [comment]
Yes, problem solved. However, paths starting with /home/ did not work, but full mnt/c/... did. Thank you. If I have further problems I will create a new issue, or I will continue here, as you prefer.

**Comment by MaestSi** [comment]
It could be that `/home/avalo` is a path inside WSL, but it is physically located on the disk at `/mnt/c` etc...?
In any case, glad it worked.
SM

**Comment by sebastianavalon** [comment]
"It could be that /home/avalo is a path inside WSL, but it is physically located on the disk at /mnt/c etc...?" 
- I guess you're right, 'home', does not physically exist on the disk.

**Comment by sebastianavalon** [comment]
Ok. I've almost reached the end. I am using only single barcodes, small files ~30mb. The biggest problem is the database, because from the "true" position downloading the database didn't work, I saw in previous issues that other people had problems with it, so I downloaded SILVA manually. Now everything is processed almost to the end. Now the problem is with the last step 'diversityAnalyses (1)' -> it can't find from 'table-collapsed-absfreq-level6.qza' the table that I really care about. And in fact in the results there is only the table 'feature-table-relfreq-level1' and OTUs assigned only to bacteria, and where are the rest of the taxonomic levels? I ran the same barcode through Epi2me and Kraken generated several dozen lines to the genus level. I don't know if I downloaded the wrong SILVA? Or is the problem somewhere else?

Best,
Sebastian

**Comment by MaestSi** [comment]
Hi, in the **collapseTables** process there is this line:
`num_levels=\$(echo \$(cat ${params.dbTaxonomyTsv} | head -n2 | tail -n1 | cut -f2 | grep -n -o \";\" | wc -l) + 1 | bc)`
where the number of semicolumn-separated (;) levels in the database are counted. It could be that in your **dbTaxonomyTsv** file levels are not separated with this character?
Best,
SM

**Comment by shanptom** [comment]
Hi Simone,

I had the same issue with collapseTables function. When I used [Silva 138 SSURef NR99 full-length sequences](https://data.qiime2.org/2023.9/common/silva-138-99-seqs.qza) and [Silva 138 SSURef NR99 full-length taxonomy](https://data.qiime2.org/2023.9/common/silva-138-99-tax.qza) files from QIIME2 site. I tried setting the value as `num_levels=6`, which resolved the issue, will it affect the pipeline in any way? Also in another thread(#81) you mentioned using alignment-based classifiers, does the above Silva dbs satisfy this requirement? I am also confused about the ideal range for `minIdentity` and `minQueryCoverage` when using Silva or Greengenes databases, when I tried 97 and 90% respectively in Epi2Me most of the sequences were unclassified. Please let me know if you have any recommendations.
Thank You for your support and contributions.
Shan

**Comment by MaestSi** [comment]
Hi,
the above fasta and tsv files, in QIIME2, in general, can be used both for training a Naive-Bayes classifier and as a reference database for alignment-based methods. In MetONTIIME, only 2 alignment-based methods (Blast and VSEARCH) are available. Those attached files should be perfectly fine. After unzipping them, you should set the fasta and tsv files as values for  `dbSequencesFasta` and `dbTaxonomyTsv` parameters, respectively, also in case you set the `importDb` process to false and meant to use pre-built qza files. As a temporary fix, you can manually set the number of levels to 7 (that is the number of levels in the attached tsv) and set `taxaLevelDiversity` to 6, it will not affect the pipeline. `minIdentity `should be set based on the expected error rate of your sequencing reads and the amount of differences you are willing to accept. A value of 0.90-0.95 may be ok, if using the latest R10.4.1 chemistry with sup base-calling. `minQueryCoverage` may be set to 0.8, if your reads do not extend further compared to the gene in the database (I am thinking of cases where one may have amplified 16S-ITS-23S amplicon, but the database may contain only 16S gene, for example).
Hope this helps.
Best,
SM

**Comment by shanptom** [comment]
Hi Simone,

Thank you for the detailed explanation and quick response.
