### ISSUE TITLE
threads absent in the blastn code block

### ISSUE THREAD

**Issue by splaisan** [MaestSi/MetONTIIME#13]
Hi Simone,
I am back to using your nice tool and noticed that you did not put THREADS in the Blast block.
My blast job is huge (SILVA x many reads) and taking already hours.
is there a reason for not having multithreaded blast?
Thanks,
Stephane

**Comment by splaisan** [comment]
sorry, this was already discussed before, it is at the qiime side, I close this, apologies ;-)

**Comment by MaestSi** [comment]
Hi Stephane,
as you have probably read in QIIME2 forum, I made a feature request for multi-threaded blast. This will hopefully be available in the next QIIME2 release, due on the end of February.
Simone

**Comment by splaisan** [comment]
Hi Simone,
Yes I discovered it after posting at your place.
they promised me last year to also add filter parameters to Vsearch too but this was postponed. Hope they will do it soon
Best
Stephane

**Comment by MaestSi** [comment]
Hi Stephane, I just wanted to inform you that the Vsearch parameters for speeding up the search are now exposed. I did a quick test with demo data and found it to be very fast. Unfortunately Blast is still single threaded, as the current implementation calls Blast with `-query` and `-subject` parameters that do not support multi-threading. For speeding it up, the database should be indexed on the fly with `makeblastdb`, and then the multi-threaded search could be performed by searching the database with `-query` and `-db` parameters. This may be implemented in a future release, but now I have the feeling that Vsearch performs in a comparable or maybe even better way. If you get the chance to do some other comparisons, please let me know!
Thanks,
Simone
