### ISSUE TITLE
How to analysis MinIon transcriptome data?

### ISSUE THREAD

**Issue by sekhwal** [MaestSi/MetONTIIME#15]
Hi,
Can the pipeline (MetONTIIME) be used for  MinIon transcriptome data. Please help me to suggest any pipeline for MinIon sequencing and analysis to look at a viral transcriptome.

**Comment by MaestSi** [comment]
Hi,
no, the MetONTIIME pipeline is only meant for meta-barcoding studies, namely the identification of taxa present in a mixed sample based on the sequence of a marker gene.
You may find what you are looking for in [this page](https://github.com/CDCgov/SARS-CoV-2_Sequencing).
Best,
Simone

**Comment by sekhwal** [comment]
Ok! Thanks.
