### ISSUE TITLE
Disk quota error when "QIIME is caching your current deployment for improved performance."

### ISSUE THREAD

**Issue by timregan** [MaestSi/MetONTIIME#18]
Hi,
Very glad you developed this pipeline, looks like it has everything I need! Having trouble getting started though.
Every time I activate the MetONTIIME_env, I get the following message
`QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.`
Which seems normal. But this is immediately followed by a lot of errors ending in `OSError: [Errno 122] Disk quota exceeded`
My conda envs directory (where the MetONTIIME_env is located) has hundreds of free Gb, but my home directory does not.
I'm wondering where QIIME is trying to perform this caching, and if this sounds like the problem? 
If it is, how can I can change it to somewhere I know has lots of space?

Many thanks,
Tim

**Comment by MaestSi** [comment]
Dear Tim,
I guess the issue is due to the temporary directory used by QIIME2, possibly being `/tmp` directory.
Did you try to run:
`export TMPDIR=/path/to/free/disk`
Let me know if that solves the issue!
Simone

**Comment by timregan** [comment]
Thanks Simone, 
That's exactly the sort of thing that looks like it's causing a problem. 
But changing the TMPDIR didn't work.. 
Do you know a way I can verify the exact path which QIIME2 is trying to access?
Tim

**Comment by timregan** [comment]
Sorry! I should have guessed... It was because I moved my conda environments, updated my .condarc, but hadn't deleted all of the old packages. So some were still in my home directory, which was out of space.
All good now! Thanks again.

**Comment by MaestSi** [comment]
Hi Tim,
glad you solved it. I asked [QIIME2 developers](https://github.com/qiime2/qiime2/issues/232) and they suggested a list of environment variables to be edited, which may be involved in the temporary directory location. Please have a look at that post in case you want to find a more long-term solution.
Simone
