### ISSUE TITLE
Please help- dont really understand the instruction

### ISSUE THREAD

**Issue by amsyarimorni** [MaestSi/MetONTIIME#23]
I am very new to coding environment and get confused with:

Then, after completing MetONTIIME installation, set the MINICONDA_DIR variable in config_MinION_mobile_lab.R to the full path to miniconda3 directory.

Could someone help me to understand this sentence? Your help is much appreciated

**Comment by MaestSi** [comment]
Hi,
miniconda is a package manager that you can use to easily install other software with a single command. Also **MetONTIIME** requires a miniconda3 installation to create a dedicated environment where to install all the required dependencies. If you installed miniconda3, you will tipically have a _miniconda3_ directory somewhere in your pc (e.g. in ~/miniconda3, but it depends on where you chose to install it). For **MetONTIIME** to find all the software, you need to specify where it has to look for them. Therefore, you should open the config file _config\_MinION\_mobile\_lab.R_  and set the value of the _MINICONDA\_DIR_: variable to the appropriate directory. For example, in my own file I have:
`MINICONDA_DIR <- "/home/simone/miniconda3"`
Is it clearer now?
Simone

**Comment by amsyarimorni** [comment]
Thanks Simone

I see.. is this a command that I suppose to write in the terminal?

I wrote in terminal and got this:

(base) amsyarimorni@Amsyaris-MacBook-Pro ~ % Miniconda_dir <-/Users/amsyarimorni/opt/miniconda3
zsh: no such file or directory: -/Users/amsyarimorni/opt/miniconda3

**Comment by MaestSi** [comment]
No, you don't have to write it in the terminal. You have to write it in the config_MinION_mobile_lab.R file. Have you followed previous instructions in the README?
Simone

**Comment by amsyarimorni** [comment]
Yes I did followed the previous instructions in the README.

And I think its clearer now, just one quick question: for the Miniconda_dir, I need to mkdir the folder manually right?

Thanks!

**Comment by MaestSi** [comment]
No, you don't have to create the miniconda dir manually. If you followed the previous steps, you should have installed miniconda, so you should already have the directory. Moreover, if you ran the ./install.sh script, it should have suggested you where the miniconda directory is located on your computer.
P.s.: The pipeline is designed to work with Ubuntu systems, I don't think it will work with Mac.
Simone

**Comment by amsyarimorni** [comment]
I see.. then the best way is for me is to run the Ubuntu system first. Will go towards that direction. Thanks by the way for developing this pipeline! 

Amsyari

**Comment by MaestSi** [comment]
You're welcome!
Simone
