### ISSUE TITLE
speedup idea

### ISSUE THREAD

**Issue by splaisan** [MaestSi/MetONTIIME#3]
Maybe silly as I do not know qiime yet but could you split the fastq data into many smaller bins, run your pipeline on each in parallel and merge back at some point before finishing the workflow.
I did that for my insilico bbmap search steps and could saturate my cpus and gain a lot of compute time on 88 cores.
If the blast+ step could be map-reduced that way, I think the whole workflow would speed up quite a lot.
Again, I am not aware of merging capabilities after blasting.

+> found this http://qiime.org/tutorials/parallel_qiime.html. Is it for Qiime1 or also for 2?

**Comment by MaestSi** [comment]
Hi Stephane,
the link you sent is for QIIME1. I guess that what you say should be feasible. However, at the moment I don't have the time to try implementing it. In case, I'll let you know!
Simone

**Comment by MaestSi** [comment]
Hi, I just added an option for choosing between Blast+ and Vsearch taxonomic classifier. The latter supports multi-threading, therefore it should be faster and optimized in case multiple threads are available. I am going to close this feature request.
