### ISSUE TITLE
Analyze Nanopore fastq reads of viral genome?

### ISSUE THREAD

**Issue by sekhwal** [MaestSi/MetONTIIME#33]
Hi, I have some Nanopore fastq reads (8 files) of viral genome. Please let me know if I can use MetONTIIME pipeline to analyze these data if so which reference database I should use.

**Comment by MaestSi** [comment]
Hi,
yes, although the pipeline is mainly intendend for analysing meta-barcoding data, it should be possible to use MetONTIIME pipeline to analyze viral whole genomes. 
I did a quick test with [Viral RefSeq genomes](https://www.ncbi.nlm.nih.gov/genome/viruses/), which you can download by clicking on [View all RefSeq and Neighbor nucleotide records](https://www.ncbi.nlm.nih.gov/nuccore/?term=Viruses[Organism]%20NOT%20cellular%20organisms[ORGN]%20NOT%20wgs[PROP]%20NOT%20gbdiv%20syn[prop]%20AND%20(srcdb_refseq[PROP]%20OR%20nuccore%20genome%20samespecies[Filter])) and click on Send to -> Complete Record, Choose destination: File, Format: Fasta -> Create File. After downloading the fasta file, you can import it with **Import_database.sh** script and you are ready to go. In alternative, if you want a more fine control on which read aligned to which virus and how (alignment identity, query coverage), then I suggest you to use [MetaBlast](https://github.com/MaestSi/MetaBlast) with the same database.
Ciao,
Simone

**Comment by sekhwal** [comment]
Thank you very much for the updates. I will do a try and catch back if I need any assistance.

**Comment by MaestSi** [comment]
Ok, feel free to reopen the issue, in case something is not working!
Ciao,
Simone
