### ISSUE TITLE
IMPORT DATABASE QUESTION

### ISSUE THREAD

**Issue by dloukovi** [MaestSi/MetONTIIME#36]
Dear all,

I have downloaded **Silva 138 SSURef NR99 full-length sequences** & **Silva 138 SSURef NR99 full-length taxonomy** .qza files from the link: https://docs.qiime2.org/2021.8/data-resources/#taxonomy-classifiers-for-use-with-q2-feature-classifier
These are pre-formatted  marker gene reference databases.

Should I import them with QIIME tools or they are ready to use them in MetONTIIME? If I have to import them, can you please give me the exact command lines??

Thanks a lot!!

**Comment by MaestSi** [comment]
Hi, they are ready to use with MetONTIIME pipeline!
Please let me know if you have any issues with the analysis.
Simone

**Comment by MaestSi** [comment]
Hi, I am going to close the issue, assuming my previous answer solved it. If this is not the case, please feel free to reopen it.
Simone

**Comment by dloukovi** [comment]
Hi Simone, yes please. I am deeply sorry that I forgot to close it. Problem solved!
