### ISSUE TITLE
setting minimum sequence lenght when running MetONTIIME directly from fastq.gz files

### ISSUE THREAD

**Issue by dloukovi** [MaestSi/MetONTIIME#38]
Dear all, I have ready fastq.gz files from ONT guppy basecaller. I have run them in MetONTIIME and everything seems ok. However, I want to filter the sequences based on read length (e.g. keep sequences above 1000bp). Can I add a parameter in the command in order to do this??

Thanks a lot!!

**Comment by MaestSi** [comment]
Hi, you can prefilter them using something like:
`zless reads.fastq.gz | NanoFilt  -l 1000 | gzip > reads.filtered.fastq.gz`
Let me know if it works!
Simone

**Comment by dloukovi** [comment]
Thanks Simone!!!!
