### ISSUE TITLE
consensus taxonomy question

### ISSUE THREAD

**Issue by dloukovi** [MaestSi/MetONTIIME#39]
Dear all,

do you propose to set maximum hits for sequences equal to 1 or should I put maximum hits to 3 and study the consensus taxonomy?? How do I interpret the consensus taxonomy results?? I put maximum hits equal to 3 and in some cases I get in my results the number 1 and in other cases the value 0.6.

Thanks!!!

**Comment by MaestSi** [comment]
Hi,
I suggest you to read [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5956843/) for a clear explanation of consensus taxonomy assignment. The value you should set depends on the balance between getting all species-level assignments and avoiding wrong species-level assignments in case of similar species. 3 seems to be a good compromise to me, but if you are interested in species-level assignments only (which are known to be not always accurate based on 16S gene only) then try out 1, but also increase your minimum alignment identity to something like 0.90 or 0.95, depending on which base-caller and chemistry version you are using, which reflects on the quality of your reads.
I think 0.6 stands for 2 out of 3 top hits supporting that taxa, and 1 stands for 3 out of 3 hits supporting that taxa. I think the threshold is set at 0.51 by default, so if at least 2 out of 3 top hits agree at species-level, then you are getting species-level assignment for that read. I hope I was clear enough.
Simone

**Comment by dloukovi** [comment]
Thanks Simone, I really appreciate your help!!!
