### ISSUE TITLE
remove Unassigned as option

### ISSUE THREAD

**Issue by splaisan** [MaestSi/MetONTIIME#4]
I do not like th eunassigned because they compress some of my conditions and in my case could be removed as they arise from different PCR primer pairs.

Could you consider adding an option doing

```
qiime taxa filter-table \
  --i-table table.qza \
  --i-taxonomy taxonomy.qza \
  --p-exclude Unassigned \
  --o-filtered-table table-no-Unassigned.qza
 
qiime taxa barplot \
  --i-table table-no-Unassigned.qza \
  --i-taxonomy taxonomy.qza   \
  --m-metadata-file sample-metadata.tsv \
  --o-visualization taxa-bar-plots-no-Unassigned.qzv
```

instead of (or extra to) your straight command

```
qiime taxa barplot \
  --i-table table.qza \
  --i-taxonomy taxonomy.qza \
  --m-metadata-file $SAMPLE_METADATA \
  --o-visualization taxa-bar-plots.qzv
```

The plot looks much nicer after this for me.

I do not know what other commands should be changed downstream when doing this, I just made the plot with the viewer and it worked as I wished it

**Comment by MaestSi** [comment]
Hi Stephane,
for now I simply added your command, so that another barplot without "Unassigned" is generated. I have not modified any files downstream yet. If you would like to have some files in particular without the Unassigned, let me know!
