### ISSUE TITLE
Identity score in MetONTIIME results

### ISSUE THREAD

**Issue by dloukovi** [MaestSi/MetONTIIME#40]
Dear Simone,

can I find somewhere in the MetONTIIME results the percentage of identity (identity score) for each assigned read??
Thanks a lot!!

**Comment by MaestSi** [comment]
Hi, unfortunately not, I remember QIIME2 developers already commented on that. You may have a look at QIIME2 forum for similar discussions, this is something not dependent on MetONTIIME, but on QIIME2 implementation of Vsearch.
SM

**Comment by MaestSi** [comment]
Hi, if you are still interested in the topic, starting from QIIME 2022.8 (corresponding to MetONTIIME-v1.17.0) both taxonomic classifiers output search_results.qza file, where you can find results in [BLASTn output format 6](https://www.metagenomics.wiki/tools/blast/blastn-output-format-6).
Best,
SM

**Comment by dloukovi** [comment]
Dear Simone,

thanks a lot for the information! I have another question and I would like your help please. Apart from my bacterial samples I have some eukaryotic samples that I want to analyze. So I started downloading from NCBI some fasta files (that contain eukaryotic sequences) to use as reference databases in MetONTTIME. As a start, I used RESCRIPT to produce sequence.qza and taxonomy.qza artifacts. However, when I started to run MetONTIIME, my desktop reached a point in the analysis and then did nothing (it stopped to some point). The nohup.out file has reached to step 8 and then nothing.
After that, I used Import_database.sh script for importing a fasta file (eukaryotic sequences) in order to produce the artifacts. The script downloaded some taxonomy files from NCBI (entrez qiime<https://github.com/bakerccm/entrez_qiime> was also installed) and produced the sequence.qza file. However, it cannot produce the corresponding taxonomy.qza artifact. I get an error saying something like the following: 'cannot find (or 'cannot output', I don't remember exactly) /home/dimitrios/MetONTIIME/taxonomy-accesion-sequence.txt'. It also says 'invalid input path'

Can you help me somehow??

Thanks a lot!

Dimitrios

[cid:373084ae-dae9-4a54-840e-30a51093f806]
Dr. Dimitrios Loukovitis
Junior Researcher
Research Institute of Animal Science
General Directorate of Agricultural Research
Hellenic Agricultural Organisation "Demeter"
Paralimni Giannitsa, 58100, Pella
Mobile: 6945418261

e-mail: ***@***.***
            ***@***.***
Skype: dimitrios.loukovitis1



________________________________
Από: Simone Maestri ***@***.***>
Στάλθηκε: Τρίτη, 30 Αυγούστου 2022 6:02 μμ
Προς: MaestSi/MetONTIIME ***@***.***>
Κοιν.: dloukovi ***@***.***>; Author ***@***.***>
Θέμα: Re: [MaestSi/MetONTIIME] Identity score in MetONTIIME results (Issue #40)


Hi, if you are still interested in the topic, starting from QIIME 2022.8 (corresponding to MetONTIIME-v1.17.0) both taxonomic classifiers output search_results.qza file, where you can find results in BLASTn output format 6<https://www.metagenomics.wiki/tools/blast/blastn-output-format-6>.
Best,
SM

**Comment by MaestSi** [comment]
Dear Dimitrios,
you could try running `Import_database.sh` script providing the full path to the fasta file, if you haven't already.
Let me know if this solves the issue.
Best,
Simone

**Comment by dloukovi** [comment]
Dear Simone,

unfortunately I get the same error message (please see below). I have also attached the fasta file (mytilus.fasta) in order to give it a try if you wish...

***@***.***:~$ conda activate MetONTIIME_env
(MetONTIIME_env) ***@***.***:~$ cd MetONTIIME
(MetONTIIME_env) ***@***.***:~/MetONTIIME$ ./Import_database.sh /home/dimitrios/MetONTIIME/mytilus.fasta
WARNING: A conda environment already exists at '/home/dimitrios/miniconda3/envs/entrez_qiime_env'
Remove existing environment (y/[n])? n


CondaSystemExit: Exiting.

./Import_database.sh: line 22: activate: No such file or directory
Requirement already satisfied: numpy in /home/dimitrios/miniconda3/envs/MetONTIIME_env/lib/python3.8/site-packages (1.23.2)
Collecting cogent
  Using cached cogent-1.9.tar.gz (1.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_80f9cx3/cogent_4a98d3dfbc934be3bac4753805d7d21a/setup.py", line 61
          print "Failed to build html due to ImportErrors for sphinx"
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Failed to build html due to ImportErrors for sphinx")?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
  File "./entrez_qiime/entrez_qiime.py", line 192
    print "Need to supply either FASTA file or accession number list as input."    # should never get here because either -i or -L is a required argument.
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Need to supply either FASTA file or accession number list as input."    # should never get here because either -i or -L is a required argument.)?

CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


./Import_database.sh: line 52: activate: No such file or directory
Imported /home/dimitrios/MetONTIIME/mytilus.fasta as DNAFASTAFormat to /home/dimitrios/MetONTIIME/mytilus_sequence.qza
Usage: qiime tools import [OPTIONS]

  Import data to create a new QIIME 2 Artifact. See https://docs.qiime2.org/
  for usage examples and details on the file types and associated semantic
  types that can be imported.

Options:
  --type TEXT             The semantic type of the artifact that will be
                          created upon importing. Use --show-importable-types
                          to see what importable semantic types are available
                          in the current deployment.                [required]
  --input-path PATH       Path to file or directory that should be imported.
                                                                    [required]
  --output-path ARTIFACT  Path where output artifact should be written.
                                                                    [required]
  --input-format TEXT     The format of the data to be imported. If not
                          provided, data must be in the format expected by the
                          semantic type provided via --type.
  --show-importable-types Show the semantic types that can be supplied to
                          --type to import data into an artifact.
  --show-importable-formats
                          Show formats that can be supplied to --input-format
                          to import data into an artifact.
  --help                  Show this message and exit.

                    There was a problem with the command:
 (1/1) Invalid value for '--input-path': Path
  '/home/dimitrios/MetONTIIME/mytilus_accession_taxonomy.txt' does not exist.



[cid:f7daa854-1c7a-48c8-b3bb-f32e868e5883]
Dr. Dimitrios Loukovitis
Junior Researcher
Research Institute of Animal Science
General Directorate of Agricultural Research
Hellenic Agricultural Organisation "Demeter"
Paralimni Giannitsa, 58100, Pella
Mobile: 6945418261

e-mail: ***@***.***
            ***@***.***
Skype: dimitrios.loukovitis1



________________________________
Από: Simone Maestri ***@***.***>
Στάλθηκε: Τετάρτη, 9 Νοεμβρίου 2022 11:51 πμ
Προς: MaestSi/MetONTIIME ***@***.***>
Κοιν.: dloukovi ***@***.***>; Author ***@***.***>
Θέμα: Re: [MaestSi/MetONTIIME] Identity score in MetONTIIME results (Issue #40)


Dear Dimitrios,
you could try running Import_database.sh script providing the full path to the fasta file, if you haven't already.
Let me know if this solves the issue.
Best,
Simone

**Comment by MaestSi** [comment]
I don't see the fasta file attached.
As a last test, you could try de-activating MetONTIIME environment before running `Import_database.sh` script. If this does not run, it means there probably is an issue with the entrez_qiime_env conda environment. In case, you could try re-building the environment from scratch.
Simone

**Comment by dloukovi** [comment]
Ok Simone, I will try it and let you know! I have attached again the fasta file. Can you see it now??

Dimitrios

[cid:bc4945d2-4400-4afe-b2b0-2bc424a94999]
Dr. Dimitrios Loukovitis
Junior Researcher
Research Institute of Animal Science
General Directorate of Agricultural Research
Hellenic Agricultural Organisation "Demeter"
Paralimni Giannitsa, 58100, Pella
Mobile: 6945418261

e-mail: ***@***.***
            ***@***.***
Skype: dimitrios.loukovitis1



________________________________
Από: Simone Maestri ***@***.***>
Στάλθηκε: Τετάρτη, 9 Νοεμβρίου 2022 3:09 μμ
Προς: MaestSi/MetONTIIME ***@***.***>
Κοιν.: dloukovi ***@***.***>; Author ***@***.***>
Θέμα: Re: [MaestSi/MetONTIIME] Identity score in MetONTIIME results (Issue #40)


I don't see the fasta file attached.
As a last test, you could try de-activating MetONTIIME environment before running Import_database.sh script. If this does not run, it means there probably is an issue with the entrez_qiime_env conda environment. In case, you could try re-building the environment from scratch.
Simone

**Comment by MaestSi** [comment]
No, you may need to change the file extension to txt.
SM

**Comment by dloukovi** [comment]
now???
[cid:51961849-50ba-4eab-9ad6-6c968abdc1c7]
Dr. Dimitrios Loukovitis
Junior Researcher
Research Institute of Animal Science
General Directorate of Agricultural Research
Hellenic Agricultural Organisation "Demeter"
Paralimni Giannitsa, 58100, Pella
Mobile: 6945418261

e-mail: ***@***.***
            ***@***.***
Skype: dimitrios.loukovitis1



________________________________
Από: Simone Maestri ***@***.***>
Στάλθηκε: Τετάρτη, 9 Νοεμβρίου 2022 3:14 μμ
Προς: MaestSi/MetONTIIME ***@***.***>
Κοιν.: dloukovi ***@***.***>; Author ***@***.***>
Θέμα: Re: [MaestSi/MetONTIIME] Identity score in MetONTIIME results (Issue #40)


No, you may need to change the file extension to txt.
SM

**Comment by dloukovi** [comment]
[mytilus.txt](https://github.com/MaestSi/MetONTIIME/files/9971456/mytilus.txt)

**Comment by dloukovi** [comment]
ok now??

**Comment by MaestSi** [comment]
Yes.
SM

**Comment by MaestSi** [comment]
Hi Dimitrios,
attached you can find QIIME2 artifacts for mytilus sequence you sent me.
[mytilus_artifacts.zip](https://github.com/MaestSi/MetONTIIME/files/9978908/mytilus_artifacts.zip)
SM

**Comment by dloukovi** [comment]
Thank you very very much Simone, I will try them and let you know. Did you try something different in your MetONTIIME installation in order to produce the artifacts? I still cannot figure out  how to do it in my desktop. I always get error messages (I have even reinstalled the  entrez qiime<https://github.com/bakerccm/entrez_qiime> enviroment)....

[cid:fcf824ce-bfd6-4132-876a-b8374b0edd49]
Dr. Dimitrios Loukovitis
Junior Researcher
Research Institute of Animal Science
General Directorate of Agricultural Research
Hellenic Agricultural Organisation "Demeter"
Paralimni Giannitsa, 58100, Pella
Mobile: 6945418261

e-mail: ***@***.***
            ***@***.***
Skype: dimitrios.loukovitis1



________________________________
Από: Simone Maestri ***@***.***>
Στάλθηκε: Πέμπτη, 10 Νοεμβρίου 2022 10:40 πμ
Προς: MaestSi/MetONTIIME ***@***.***>
Κοιν.: dloukovi ***@***.***>; Author ***@***.***>
Θέμα: Re: [MaestSi/MetONTIIME] Identity score in MetONTIIME results (Issue #40)


Hi Dimitrios,
attached you can find QIIME2 artifacts for mytilus sequence you sent me.
mytilus_artifacts.zip<https://github.com/MaestSi/MetONTIIME/files/9978908/mytilus_artifacts.zip>
SM

**Comment by MaestSi** [comment]
No, I just did a fresh installation of entrez_qiime environment, to be sure it could still be installed properly. Did you get any errors during the installation? Were the files downloaded from NCBI as expected? If unsure, remove taxonomy directory before rerunning the script.
This is the portion of the code downloading files, you could also try to run this outside the script:
```
if [ ! -d "taxonomy" ]; then
  mkdir taxonomy
  cd taxonomy
  wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz
  gunzip nucl_gb.accession2taxid.gz
  wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_wgs.accession2taxid.gz
  gunzip nucl_wgs.accession2taxid.gz
  cp nucl_gb.accession2taxid nucl_merged.accession2taxid
  tail -n+2 nucl_wgs.accession2taxid >> nucl_merged.accession2taxid
  rm nucl_gb.accession2taxid nucl_wgs.accession2taxid
  mkdir taxdump
  cd taxdump
  wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
  tar -zxvf taxdump.tar.gz
  cd ../..
fi

```
