### ISSUE TITLE
issue with Vsearch

### ISSUE THREAD

**Issue by asogg** [MaestSi/MetONTIIME#43]
Hello Simone,
i run the pipeline with ./Launch_MinION_mobile_lab.sh but it fails to obtain the taxa_bar_plot.qzv and taxonomy.qzv. also in the logfile there isn't any apparent failure *i think so..

**Comment by MaestSi** [comment]
Hi, could you please share the nohup.out file, the command you used and the config_MinION_mobile_lab.R files?
Thanks;
Simone

**Comment by asogg** [comment]
[nohup.txt](https://github.com/MaestSi/MetONTIIME/files/8140717/nohup.txt)
can you open the file

**Comment by MaestSi** [comment]
Hi, yes, I can open it. In the nohup.out file I see:
`No space left on device`
So, probably you ran out of space. Try removing all directories created by MetONTIIME, freeing some space, and rerunning the pipeline.
Simone

**Comment by asogg** [comment]
perfect, i will check right now. 
thank you
Alessio

**Comment by asogg** [comment]
Hi Simone,
i have removed all the MetONTIIME directories and rerun the pipeline and was ok .
thank you
Alessio
