### ISSUE TITLE
Question: Update

### ISSUE THREAD

**Issue by tamara-nano** [MaestSi/MetONTIIME#44]
Dear MaestSi,

How do I correctly update the qiime2 and the new MetONTIME v1.15.0 release on my exisiting metontiime software? 
Is it simply sudo apt-get update and path to the new metontiime-master.zip file or something like that or do I have to follow the whole installation path again?

Thank you very much!

Best wishes,
Tamara

**Comment by MaestSi** [comment]
Hi Tamara,
I think the safest option would be to copy your config file somewhere on your machine, rename or delete MetONTIIME directory, and then repeat the installation with:
```
git clone https://github.com/MaestSi/MetONTIIME.git
cd MetONTIIME
chmod 755 *
./install.sh

```
After completing the installation, you can copy back your config file with all desired options.
Best,
Simone

**Comment by MaestSi** [comment]
Hi Tamara, I am going to close the issue assuming you were able to succesfully update the pipeline. If this is not the case, please reopen the issue.
Best,
Simone
