### ISSUE TITLE
update to Kit12 chemistry?

### ISSUE THREAD

**Issue by tamara-nano** [MaestSi/MetONTIIME#48]
Hey Simone,

I was wondering if you're planning to update your wonderful pipeline to the new kit12/14 chemistry, flowcells and super accuracy basecalling? :-)

With best regards,
Tamara

**Comment by MaestSi** [comment]
Ciao Tamara,
I think I may only have to introduce some adjustments in the preprocessing step (MinION_mobile_lab.R), while the remaining scripts should work as they are, just adjusting parameters to make the alignment more stringent. Actually I never tested the pipeline on such data, but if you are able to provide me with a raw fast5 file with a couple thousand reads, I'm happy to test it.
Best,
Simone

**Comment by tamara-nano** [comment]
Yeah, i've got some test-files with Zymobiomics DNA Microbiome Standard from kit12 with standard 27F and 1492R primer (not barcoded). The whole run has 40gb of which each fast5 file has ~100mb. Let me know how much from it you would need and how to provide them to you. 
Best,
Tamara

**Comment by MaestSi** [comment]
I think one single fast5 file should be enough to test! I think Google Drive (or whatever you prefer) should work.
Best,
Simone

**Comment by MaestSi** [comment]
Ciao Tamara,
I just slightly updated the preprocessing pipeline to enable demultiplexing to be skipped and adjusted some parameters. With the relevant parameters reported below, I tested the pipeline on the fast5 you sent me.

```
kit <- "SQK-LSK112"
flowcell <- "FLO-MIN112"
conf_basecalling_flag <- 1
conf_par_basecalling <- "-c dna_r10.4_e8.1_hac.cfg -x 'auto' --gpu_runners_per_device 1"
skip_demultiplexing_flag <- 1
min_seq_length <- 1200
max_seq_length <- 1600
primers_length <- 25
CLASSIFIER <- "Vsearch"
MAX_ACCEPTS hits is retrieved
MAX_ACCEPTS <- 3
QUERY_COV <- 0.8
ID_THR <- 0.90
```
Atttached, you can find the taxa barplot I obtained. You can rename it to remove the ".txt" suffix and upload it to [QIIME2 View](https://view.qiime2.org): [taxa-bar-plots.qzv.txt](https://github.com/MaestSi/MetONTIIME/files/9269854/taxa-bar-plots.qzv.txt).
Of course you can play around a little bit with parameters. In case, please let me know about your tests!
Best,
Simone
