### ISSUE TITLE
Naive Bayes taxonomic classification with ONT?

### ISSUE THREAD

**Issue by msmcfarlin** [MaestSi/MetONTIIME#53]
Hello,

I have been following the MetONTIIME pipeline for analysis of full length 16S ONT sequences from human oral microbiome samples. I've been going through each step of your pipeline and I saw that the taxonomic classification options were either BLAST or VSEARCH but since I've used the naive bayes method in QIIME2 before with Illumina sequences I decided to try that code with my ONT sequences, with the SILVA database for reference. 

My classification results are quite puzzling though as the output is extremely high in sequences only assigned the domain Archaea, ~35% of all sequences, compared to what I would expect in this microbiome given prior studies. Is there a reason you didn't include the naive bayes method in your pipeline? Should I be avoiding that method with ONT sequences? Any other thoughts on why this could be happening?

Thank you for your time! I really appreciate your development of a pipeline in QIIME2 for nanopore sequences.

-Mike

**Comment by MaestSi** [comment]
Dear Mike,
I never tested Naive-Bayes
classifier from QIIME2, but I previously tested the RDP classifier on old Nanopore data (around 2017, with about 15% error rate). Based on my preliminary tests, I noticed that such algorithms may be more sensitive to sequencing errors, which are responsible for spurious k-mers, causing mis-assignments. With novel sequencing chemistries and base-callers, I’m quite confident Naive-Bayes classifiers may perform quite well, but I should see or do some benchmarking studies on mock community before adding that option to the pipeline. By the way, did you retrain the classifier using full length 16S genes and the correct primer pairs, or you just used the same classifier you used for Illumina? This may be a fundamental step to perform, if you haven’t yet.
Best,
Simone

**Comment by msmcfarlin** [comment]
Hi Simone,

I am working with full length 16S so I first tried the QIIME pretrained full length 16S classifier, then trained one myself using the primer pair that we used in case their was a difference from the QIIME full length. Both gave the same result with the ~35% unassigned Archaea. I imagine you right that the high sequencing error rate is giving the high percentage of mis-assigned sequences. I'll move on to the BLAST consensus classification method that you used. Do you have any suggestions on max hits, min query coverage, and min id threshold or literature that I should refer to?

Thank you!

Best,
Mike

**Comment by MaestSi** [comment]
Actualy I have no suggestions based on literature. But you can have a look at default parameters in the config file. I think those values should be reasonable, and you may play around with parameters’ values depending on your needs to be more/less stringent.
Simone

**Comment by msmcfarlin** [comment]
Thanks Simone, I appreciate the assistance!
