### ISSUE TITLE
error in evaluating the argument 'x' 

### ISSUE THREAD

**Issue by ysuzuki1978** [MaestSi/MetONTIIME#55]
I would very much like to use MetONTIME for long read sequences and to proceed with 16S analysis.
However, when I run Launch_MinION_mobile_lab.sh, I get the following error and it stops.

In MinION_mobile_lab.R.
*****
args <- commandArgs(trailingOnly=TRUE)
config_file_ind <- grep(x = args, pattern = "\\.R")
*****

We think that the "config_file_ind" is not working, but what is the solution?

Here is the message after the run.

**************

Welcome to MinION meta-barcoding mobile laboratory!

Raw reads directory: /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5
Basecalled reads directory: /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/basecalling
Preprocessing directory: /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/preprocessing
Reads directory: /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/analysis
Flow-cell: FLO-MIN106
Kit: SQK-PBK004
PCR primers trimming length: 25 bp
Barcodes used in this experiment: BC01, BC02, BC03, BC04, BC05, BC06, BC07, BC08, BC09, BC10, BC11, BC12
Basecalling is going to be performed by : Guppy Basecalling Software, (C) Oxford Nanopore Technologies plc. Version 6.4.2+97a7f06, minimap2 version 2.24-r1122
Basecalling model: default
Demultiplexing is going to be performed by guppy_barcoder after basecalling

Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'grep': cannot open the connection
Calls: grep -> readLines -> file -> .handleSimpleError -> h
In addition: Warning messages:
1: In file(con, "r") :
  'raw = FALSE' but '/home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/analysis/' is not a regular file
2: In file(con, "r") :
  cannot open file '/home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/analysis/': it is a directory
Execution halted

**Comment by MaestSi** [comment]
Hi, what is the exact command that you ran?
I suspect there might have been an issue either during base-calling or demultiplexing. Can you show me the content of /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/basecalling, /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/preprocessing and /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/analysis folders?
Thanks,
Simone

**Comment by ysuzuki1978** [comment]
Thank you for your comments.

/home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/analysis

-rw-rw-r-- 1 yakuri yakuri 23756 12月 20 16:07 logfile.txt
*******
Welcome to MinION meta-barcoding mobile laboratory!

Raw reads directory: /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5
Basecalled reads directory: /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/basecalling
Preprocessing directory: /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/preprocessing
Reads directory: /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/analysis
Flow-cell: FLO-MIN106
Kit: SQK-PBK004
PCR primers trimming length: 25 bp
Barcodes used in this experiment: BC01, BC02, BC03, BC04, BC05, BC06, BC07, BC08, BC09, BC10, BC11, BC12
Basecalling is going to be performed by : Guppy Basecalling Software, (C) Oxford Nanopore Technologies plc. Version 6.4.2+97a7f06, minimap2 version 2.24-r1122
Basecalling model: default
Demultiplexing is going to be performed by guppy_barcoder after basecalling
**********




The following two folders are empty.

/home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/basecalling　　
/home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/preprocessing and

**Comment by MaestSi** [comment]
Thanks for your answer. This means base-calling did not work. Accordingly, there was nothing to demultiplex, and the following script failed due to the absence of samples to analyse. Can you please show me the command you ran?
Thanks

**Comment by ysuzuki1978** [comment]
I also think the problem is that it is not being passed to GUPPY well.

The command I typed in is.

. /Launch_MinION_mobile_lab.sh ~/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5/




Launch_MinION_mobile_lab.sh 

#!/bin/bash
#
# Copyright 2021 Simone Maestri. All rights reserved.
# Simone Maestri <simone.maestri@univr.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

RAW_READS_DIR=$1
RAW_READS_DIR_FULL=$(realpath $RAW_READS_DIR)
source activate MetONTIIME_env
PIPELINE_DIR=$(realpath $( dirname "${BASH_SOURCE[0]}" ))
nohup Rscript $PIPELINE_DIR/MinION_mobile_lab.R $PIPELINE_DIR/config_MinION_mobile_lab.R $RAW_READS_DIR_FULL &
~

**Comment by MaestSi** [comment]
I don't think there was an error with the loading of the config file, otherwise none of the output directories would have been created. It could be that /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/basecalling directory was previously created during a test you performed, and now base-calling is being skipped since it already finds the folder. Please try to delete  /home/yakuri/nanopore/16S_rRNA_20221018/no_sample/20221018_1928_MN38820_FAV42892_85448306/fast5_analysis/ directory and restart the analysis.

**Comment by MaestSi** [comment]
The problem is definitely guppy_basecaller not being able to base-call your reads, no idea of what could be the reason. I'd suggest checking you have read/write permissions and free space, or trying out a different Guppy version.
SM

**Comment by ysuzuki1978** [comment]
We checked the process with the ps command and it is denied that more than one MetONTIME is running.
Changing the permissions of all MetONTIME folders to 777 does not improve the situation.
There is also 800 GB of free disk space.



Are there any solutions to the following errors?

Error in h(simpleError(msg, call)) :
error in evaluating the argument 'x' in selecting a method for function 'grep': invalid 'description' argument
Calls: grep -> readLines -> file -> .handleSimpleError -> h
Execution halted


I think it has to do with the following part of the MinION_mobile_lab.R script.

*************

args = commandArgs(trailingOnly=TRUE)

config_file_ind <- grep(x = args, pattern = "\\.R")
raw_reads_ind <- setdiff(c(1, 2), config_file_ind)

**Comment by MaestSi** [comment]
The error that you see is just a consequence of base-calling not working. You get that error when the analysis dir does not contain any fastq files. I'd suggest checking that Guppy is properly installed and working (or testing a different version).
SM

**Comment by ysuzuki1978** [comment]
After re-setting the options to pass to guppy, it started working.
I appreciate your detailed comments.
However, PycoQC is not working properly.
I will make another issue.
