### ISSUE TITLE
Guppy

### ISSUE THREAD

**Issue by ObRICa** [MaestSi/MetONTIIME#58]
Hi Simone,

I understand that MetONTIIME adopts CPU version of Guppy.
Since my basecall is taking such a long time (have been running for 16 days), I am grateful if I could use the GPU version on MetONTIIME, if possible.

I have another question about steps starting from fastq.gz files.
I have started with fastq.gz files that have already been basecalled by MinKnow, following the MetONTIIME's instructions.
However the resulted file was not divided into individual files, but rather created one big file concatenating all reads from a same BC number.

I would appreciate any suggestion.

Best regards,
Erika

**Comment by MaestSi** [comment]
Hi, you should be able to get a GPU version of Guppy working (if your hardware supports it), by setting appropriately the following parameters in the config file:
```
#conf_basecalling_flag <- 1 if you want to specify a configuration file for base-calling (and additional parameters) instead of choosing the default by specifying kit and flowcell
conf_basecalling_flag <- 1
#conf_par_basecalling is the name of the config file (and additional parameters, such as the device for GPU-accelerated basecalling) in case config_basecalling_flag <- 1
conf_par_basecalling <- "-c dna_r9.4.1_e8.1_hac.cfg --device 'auto' --gpu_runners_per_device 1"
#basecaller_dir
BASECALLER_DIR <- "/path/to/ont-guppy/bin/"
```
However, if you already have one fastq.gz file for each barcode, that is the perfect starting point for the analysis starting from fastq.gz files. So, my suggestion would be to start from these files.
SM

**Comment by ObRICa** [comment]
Hi Simone,

Thanks for your prompt reply.

>However, if you already have one fastq.gz file for each barcode, that is the perfect starting point for the analysis starting from fastq.gz files. So, my suggestion would be to start from these files.

How could it possible to get "one fastq.gz file for each barcode"? 

Erika

**Comment by MaestSi** [comment]
> However the resulted file was not divided into individual files, but rather created one big file concatenating all reads from a same BC number.

I understood you already had one fastq.gz file for each barcode, which would be ok. What is the folder structure that you have at the moment?
SM

**Comment by ObRICa** [comment]
I moved 
/Volumes/HDW-UT/20230126_1328_MC-114398_FAV40636_606634c2/fastq_pass/barcode01/*.fastq.gz
to
 /Users/xxxx/Desktop/barcode01/*.fastq.gz

Then
cat /Users/xxxx/Desktop/barcode01/*.fastq.gz > /Users/xxxx/MetONTIIME/fastq_pass/BC01.fastq.gz

Ran the command:
nohup ./MetONTIIME.sh -w /Users/xxxx/MetONTIIME/fastq_pass/ -s ./silva_132_99_16S_sequence.qza -t ./silva_132_99_16S_taxonomy.qza -n 4 -c Blast -m 1 -q 0.6 -i 0.9

**Comment by MaestSi** [comment]
This seems correct to me, a part from -f /Users/xxxx/MetONTIIME/fastq_pass/sample-metadata.tsv, that is missing.
SM

**Comment by ObRICa** [comment]
Thanks! 
It worked by adding the -f option.

**Comment by MaestSi** [comment]
Great!
Ciao,
Simone
