### ISSUE TITLE
ERROR ~ Error executing process > 'concatenateFastq'

### ISSUE THREAD

**Issue by baotg080599** [MaestSi/MetONTIIME#63]
hello,
i tried run it with my fastq.gz file but it error:
ERROR ~ Error executing process > 'concatenateFastq'

Caused by:
  Process `concatenateFastq` terminated with an error exit status (126)

Command executed:

  mkdir -p /home/caothithuylinh/Desktop/ontimev2
  mkdir -p /home/caothithuylinh/Desktop/ontimev2/concatenateFastq
  
  barcodes_dirs=$(realpath $(find /home/caothithuylinh/Desktop/ontimev2/barcode -maxdepth 1 -mindepth 1 | grep "barcode"));
  echo $barcodes_dirs
  for b in $barcodes_dirs; do
  	bn=$(basename $b);
  	f=$(find $b | grep ".fastq");
  	zless $f | gzip > /home/caothithuylinh/Desktop/ontimev2/concatenateFastq/$bn.fastq.gz;
  done

Command exit status:
  126

Command output:
  (empty)

Command error:
  docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=nxf-jkjnUa0MU3l504IZQ171OydU": dial unix /var/run/docker.sock: connect: permission denied.
  See 'docker run --help'.

Work dir:
  /home/caothithuylinh/Desktop/ontimev2/MetONTIIME/work/f5/fd7a613e78a36968b238f2d5ca5a0c

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

please, check help me, i successfully with old version

**Comment by baotg080599** [comment]
it look error in concatenatefastq process

**Comment by MaestSi** [comment]
Hi, the error:
`docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=nxf-jkjnUa0MU3l504IZQ171OydU": dial unix /var/run/docker.sock: connect: permission denied.`
means that either docker daemon is not running, or you did not do post-installation steps to let it run without administrator permissions (sudo). Please try to run `docker run hello-world`, and have a look at [this](https://docs.docker.com/engine/install/linux-postinstall/).
SM

**Comment by baotg080599** [comment]
i ran docker with administrator(sudo) but it error:
ERROR ~ Error executing process > 'concatenateFastq'

Caused by:
  Process `concatenateFastq` terminated with an error exit status (1)

Command executed:

  mkdir -p /home/caothithuylinh/Desktop/ontimev2
  mkdir -p /home/caothithuylinh/Desktop/ontimev2/concatenateFastq
  
  barcodes_dirs=$(realpath $(find /home/caothithuylinh/Desktop/ontimev2/barcode -maxdepth 1 -mindepth 1 | grep "barcode"));
  echo $barcodes_dirs
  for b in $barcodes_dirs; do
  	bn=$(basename $b);
  	f=$(find $b | grep ".fastq");
  	zless $f | gzip > /home/caothithuylinh/Desktop/ontimev2/concatenateFastq/$bn.fastq.gz;
  done

Command exit status:
  1

Command output:
  /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level6.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level4.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level5.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/sequences.qza /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level3.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/taxa-bar-plots.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level2.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level1.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/rep-seqs.qza /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level5.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/AJI298_pass_barcode01_2125d3df_42.fastq.gz /home/caothithuylinh/Desktop/ontimev2/barcode/taxonomy.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level7.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/table.qza /home/caothithuylinh/Desktop/ontimev2/barcode/demux_summary.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level7.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level1.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/taxa-bar-plots-no-Unassigned.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/table.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/collapsed_feature_tables /home/caothithuylinh/Desktop/ontimev2/barcode/taxonomy.qza /home/caothithuylinh/Desktop/ontimev2/barcode/manifest.txt /home/caothithuylinh/Desktop/ontimev2/barcode/rep-seqs.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level2.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/AJI298_pass_barcode01_2125d3df_43.fastq.gz /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level6.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level3.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/search_results.qza /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level4.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/table-no-Unassigned.qza /home/caothithuylinh/Desktop/ontimev2/barcode/AJI298_pass_barcode01_2125d3df_44.fastq.gz

Command error:
  /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level6.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level4.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level5.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/sequences.qza /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level3.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/taxa-bar-plots.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level2.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level1.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/rep-seqs.qza /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level5.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/AJI298_pass_barcode01_2125d3df_42.fastq.gz /home/caothithuylinh/Desktop/ontimev2/barcode/taxonomy.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level7.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/table.qza /home/caothithuylinh/Desktop/ontimev2/barcode/demux_summary.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level7.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level1.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/taxa-bar-plots-no-Unassigned.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/table.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/collapsed_feature_tables /home/caothithuylinh/Desktop/ontimev2/barcode/taxonomy.qza /home/caothithuylinh/Desktop/ontimev2/barcode/manifest.txt /home/caothithuylinh/Desktop/ontimev2/barcode/rep-seqs.qzv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level2.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/AJI298_pass_barcode01_2125d3df_43.fastq.gz /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level6.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_absfreq_level3.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/search_results.qza /home/caothithuylinh/Desktop/ontimev2/barcode/feature-table_relfreq_level4.tsv /home/caothithuylinh/Desktop/ontimev2/barcode/table-no-Unassigned.qza /home/caothithuylinh/Desktop/ontimev2/barcode/AJI298_pass_barcode01_2125d3df_44.fastq.gz

Work dir:
  /home/caothithuylinh/Desktop/ontimev2/MetONTIIME/work/79/94f3776154f6c871a00e76b0c67b4d

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Comment by MaestSi** [comment]
Moreover, concatenateFastq process should be set to false, if you already have one fastq.gz file for each sample.
SM

**Comment by baotg080599** [comment]
how to set to false for concatenateFastq, in your tutorial i not found it?

**Comment by MaestSi** [comment]
You have to open **metontiime2.conf** file, and at line 50 change:
`concatenateFastq = true`
to
`concatenateFastq = false`
SM

**Comment by baotg080599** [comment]
oh, i'm sorry, thanks you so much sir

**Comment by MaestSi** [comment]
No worries, let me know if you are able to make it run.
SM

**Comment by MaestSi** [comment]
Hi, I just corrected a bug causing diversityAnalysis process to start before collapseTables process was completed. Please download the updated metontiime2.nf script before re-running the pipeline.
SM

**Comment by MaestSi** [comment]
Hi, I am going to close this issue. In case there are any further issues, feel free to reopen it.
Best,
SM
