### ISSUE TITLE
folder 4e does not exist

### ISSUE THREAD

**Issue by joyleng** [MaestSi/MetONTIIME#66]
Hi

Sorry me again. I manage to run MetONTIIME but was getting an error that I see a couple of people have had before. When it got to trying to calculate diversity measures it would error saying that table-collapsed-absfreq-level6.qza does not exist. So I re-downloaded MetONTIIME as suggested on other discussions as my initial download was probably about a month ago. However I am now getting a different error nearly straight away:

ERROR ~ Error executing process > 'importDb (1)'

Caused by:
  java.io.IOException: Cannot run program "qsub" (in directory "/pub63/joyl/MetONTIIME/work/4e/885217e0535be2262e3291d3c8a2c1"): error=2, No such file or directory

I have checked and the folder 4e does not exist within the work folder. I don't know if this is linked with specifying the singularity.cacheDir on line 72 of the .conf file? I had a search and I couldn't find anyone else who has had this error. I have attached the nextflow log file which states the error in full.
[.nextflow.log](https://github.com/MaestSi/MetONTIIME/files/12185424/default.nextflow.log)

Many thanks
Joy

**Comment by MaestSi** [comment]
Hi,
based on [this discussion](https://github.com/MaestSi/MetONTIIME/issues/65#issuecomment-1643863090) we had before, it seems you didn't have pbspro job scheduler, and you should change `executor = pbspro` to `executor = local` in metontiime2.conf file.
Best,
SM

**Comment by joyleng** [comment]
Ah yes that's working now. I think I had made that change to the .conf during out previous discussion but as I downloaded everything again I had missed changing it on the new one.

Thanks again
Joy
