### ISSUE TITLE
Invalid value for '--o-bray-curtis-distance-matrix': 

### ISSUE THREAD

**Issue by baotg080599** [MaestSi/MetONTIIME#69]
it look wrong at line 529 in metontiime2.nf make me cannot run diverrsity step. So, i fixed it and run it is successfull. Please, check it.
this is my error:
Caused by:
  Process `diversityAnalyses (1)` terminated with an error exit status (1)

Command executed:

  mkdir -p /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses
  mkdir -p /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1
  
  qiime diversity core-metrics   		--i-table /home/caothithuylinh/Desktop/testOntimeV2/filterTaxa/table-Bacteria-min-freq-1-collapsed-absfreq-level1.qza   		--p-sampling-depth 10000   		--m-metadata-file /home/caothithuylinh/Desktop/testOntimeV2/MetONTIIME/sample-metadata.tsv   	--o-rarefied-table /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1/rarefied-table.qza   		--o-observed-features-vector /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1/observed-features-vector.qza   	--o-shannon-vector /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1/shannon-vector.qza   		--o-evenness-vector /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1/evenness-vector.qza   		--o-jaccard-distance-matrix /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1/jaccard-distance-matrix.qza   		--o-bray-curtis-distance-matrix /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/samplingDepth-10000-level1/bray-curtis-distance-matrix.qza   		--o-jaccard-pcoa-results /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1/jaccard-pcoa-results.qza   	--o-bray-curtis-pcoa-results /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1/bray-curtis-pcoa-results.qza   --o-jaccard-emperor /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1/jaccard-emperor.qzv   		--o-bray-curtis-emperor /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1/bray-curtis-emperor.qzv
  
  for f in $(find /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1 | grep "qza" | grep -v "distance-matrix"); do
  
  			fn=$(echo $f | sed 's/\.qza//');
  
  			qiime metadata tabulate   			--m-input-file $f   			--o-visualization $fn".qzv";
  done
  
  qiime diversity alpha-rarefaction   		--i-table /home/caothithuylinh/Desktop/testOntimeV2/filterTaxa/table-Bacteria-min-freq-1-collapsed-absfreq-level1.qza   		--p-max-depth 10000   		--m-metadata-file /home/caothithuylinh/Desktop/testOntimeV2/MetONTIIME/sample-metadata.tsv   		--o-visualization /home/caothithuylinh/Desktop/testOntimeV2/diversityAnalyses/taxa-Bacteria-samplingDepth-10000-level1/alpha-rarefaction.qzv

Command exit status:
  1

Command output:
  (empty)

Command error:
    --o-bray-curtis-distance-matrix ARTIFACT
      DistanceMatrix        Matrix of Bray-Curtis distances between pairs of
                            samples.                                  [required]
    --o-jaccard-pcoa-results ARTIFACT
      PCoAResults           PCoA matrix computed from Jaccard distances between
                            samples.                                  [required]
    --o-bray-curtis-pcoa-results ARTIFACT
      PCoAResults           PCoA matrix computed from Bray-Curtis distances
                            between samples.                          [required]
    --o-jaccard-emperor VISUALIZATION
                            Emperor plot of the PCoA matrix computed from
                            Jaccard.                                  [required]
    --o-bray-curtis-emperor VISUALIZATION
                            Emperor plot of the PCoA matrix computed from
                            Bray-Curtis.                              [required]
  Miscellaneous:
    --output-dir PATH       Output unspecified results to a directory
    --verbose / --quiet     Display verbose output to stdout and/or stderr
                            during execution of this action. Or silence output
                            if execution is successful (silence is golden).
    --recycle-pool TEXT     Use a cache pool for pipeline resumption. QIIME 2
                            will cache your results in this pool for reuse by
                            future invocations. These pool are retained until
                            deleted by the user. If not provided, QIIME 2 will
                            create a pool which is automatically reused by
                            invocations of the same action and removed if the
                            action is successful. Note: these pools are local to
                            the cache you are using.
    --no-recycle            Do not recycle results from a previous failed
                            pipeline run or save the results from this run for
                            future recycling.
    --parallel              Execute your action in parallel. This flag will use
                            your default parallel config.
    --parallel-config FILE  Execute your action in parallel using a config at
                            the indicated path.
    --use-cache DIRECTORY   Specify the cache to be used for the intermediate
                            work of this pipeline. If not provided, the default
                            cache under $TMP/qiime2/<uname> will be used.
                            IMPORTANT FOR HPC USERS: If you are on an HPC system
                            and are using parallel execution it is important to
                            set this to a location that is globally accessible
                            to all nodes in the cluster.
    --example-data PATH     Write example data and exit.
    --citations             Show citations and exit.
    --help                  Show this message and exit.
  
                      There was a problem with the command:                     
   (1/1) Invalid value for '--o-bray-curtis-distance-matrix': Directory '/home/c
    aothithuylinh/Desktop/testOntimeV2/diversityAnalyses/samplingDepth-10000-lev
    el1' does not exist, cannot save 'bray-curtis-distance-matrix.qza' into it.

Work dir:
  /home/caothithuylinh/Desktop/testOntimeV2/MetONTIIME/work/41/289bc9e25b780abf155c1196aea5d7

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

**Comment by MaestSi** [comment]
Hi,
I don't get what you edited.
In any case, you are running diversity analyses at taxonomy level 1 (which probably is just "Bacteria" and could not be very meaningful). Moreover, **diversityAnalyses** process requires more than one sample to produce alpha and beta-diversity metrics. I just edited **metontiime2.nf** script to prevent running diversity metrics with a single sample, which previously resulted in an error.
SM

**Comment by MaestSi** [comment]
Hi, I am going to close the issue. Feel free to reopen it, in case you have any further questions!
SM
