### ISSUE TITLE
COLLAPSE_TABLE PROCESS CREATES ONLY RESULTS FOR TAXONOMIC LEVEL1

### ISSUE THREAD

**Issue by dloukovi** [MaestSi/MetONTIIME#72]
WHEN RUNNING THE ANALYSIS, AFTER  'ASSIGNTAXONOMY' PROCESS IS COMPLETED, THE 'COLLAPSETABLE' PROCESS PRODUCES RESULTS ONLY FOR TAXONOMIC LEVEL 1. WHEN THE 'DIVERSITYANALYSIS' PROCESS FOLLOWS, IT CANNOT BE COMPLETED (ERROR) CAUSE IT CANNOT FIND ALL THE NECESSARY FILES (FILES FOR TAXONOMIC LEVEL6) IN THE COLLAPSE TABLES DIRECTORY

**Comment by MaestSi** [comment]
Hi, are you using a recent version of the pipeline? Which database are you using? Please provide the command you ran, the config file and error messages.
SM

**Comment by dloukovi** [comment]
Dear Simone, I am using the latest version (with nextflow and docker). I managed to adjust configurations for docker (it was not so easy for a beginner in bioinformatics...). I used the NCBI16S database (the same that EPI2ME uses). If I disable the diversity analysis process in the config file, the process is completed but produces only collapsed tables for taxonomic level 1. That's why if I enable the diversity analysis (for level 6 in config file) it comes with an error 'cannot find feature table level 6 in collapse table dir'. I have attached the config file for your consideration.

**Comment by dloukovi** [comment]
here's the attachment..
[metontiime2.zip](https://github.com/MaestSi/MetONTIIME/files/13162967/metontiime2.zip)
.

**Comment by MaestSi** [comment]
Hi, I see in the config file that you set to false importDb process, is this becuase the import already succeeded. I suspect there could be issues in the formatting of the database you used, which prevent the pipeline from recognising the taxonomy levels. Could you also please provide a few lines of taxonomy tsv (and fasta) files you are using?
Thanks,
SM

**Comment by MaestSi** [comment]
Closing the issue due to inactivity.
