### ISSUE TITLE
Adjust CPU and RAM

### ISSUE THREAD

**Issue by timyerg** [MaestSi/MetONTIIME#73]
Hi!
Thank you for developing and maintaining this tool.
I have a very basic question since I have 0 experience with docker or singularity and have no idea how to adjust profiles.

For example, here is a piece if code I want to adjust for singularity:

```
withName:assignTaxonomy{
	container = 'maestsi/metontiime:latest'
	cpus = { params.assignTaxonomy ? 6 : 1 }
	memory = { params.assignTaxonomy ? 10.GB + (2.GB * (task.attempt-1)) : 1.GB }
	errorStrategy = { task.exitStatus == 130 ? 'retry' : 'terminate' }
	maxRetries = 3
}
```
How I should adjust it here?

Is it correct for 8 CPUs?
cpus = { params.assignTaxonomy ? 6 : 8 } 

Which parameters should I modify here?
memory = { params.assignTaxonomy ? 10.GB + (2.GB * (task.attempt-1)) : 1.GB }

I am confused.

**Comment by timyerg** [comment]
Looks like it was already answered at the time I was typing this question here:
https://github.com/MaestSi/MetONTIIME/issues/71#issuecomment-1779226288

Thank you!

**Comment by MaestSi** [comment]
:)
