### ISSUE TITLE
Process error

### ISSUE THREAD

**Issue by ObRICa** [MaestSi/MetONTIIME#76]
Hello MaestSi,

I have just started to use the nextflow version of MetONTIIME.

First I was using an M1 chip mac, resulted in error probably due to the mismatch between Docker.
I switched to an Intel chip mac, but the process ends up in error.

Here is the log. I would appreciate any suggestion. Best regards.

**********
Command executed:

  mkdir -p /Users/xxxx/nextflow_MetONTIIME/MetONTIIME
  mkdir -p /Users/xxxx/nextflow_MetONTIIME/MetONTIIME/concatenateFastq
  cp /Users/xxxx/nextflow_MetONTIIME/MetONTIIME/*fastq.gz /Users/xxxx/nextflow_MetONTIIME/MetONTIIME/concatenateFastq

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 98: docker: command not found

Work dir:
  /Users/xxxx/nextflow_MetONTIIME/MetONTIIME/work/d6/3e3961533fe319ded29b03bad235cf

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
11-10 15:38:55.144 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `concatenateFastq` terminated with an error exit status (127)
11-10 15:38:55.169 [main] DEBUG nextflow.Session - Session await > all processes finished
11-10 15:38:55.170 [main] DEBUG nextflow.Session - Session await > all barriers passed
11-10 15:38:55.174 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 2; name: importDb (1); status: COMPLETED; exit: 127; error: -; workDir: /Users/xxxx/nextflow_MetONTIIME/MetONTIIME/work/12/63f5c590d59490dbfb1efe513113c4]
11-10 15:38:55.174 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=importDb (1); work-dir=/Users/xxxx/nextflow_MetONTIIME/MetONTIIME/work/12/63f5c590d59490dbfb1efe513113c4
  error [nextflow.exception.ProcessFailedException]: Process `importDb (1)` terminated with an error exit status (127)
11-10 15:38:55.178 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local) - terminating tasks monitor poll loop
11-10 15:38:55.179 [main] DEBUG n.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=2; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=33ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=6; peakMemory=10 GB; ]
11-10 15:38:55.347 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
11-10 15:38:55.367 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

**Comment by MaestSi** [comment]
Hi, here is the error:
`docker: command not found`
This means that you probably forgot to start `Docker Desktop` on your Mac. As a test, you may open a terminal and check that `docker --help` command results in the same error. Conversely, with Docker daemon running, you should be able to find it in the terminal, and the Nextflow pipeline should find it as well.
SM

**Comment by ObRICa** [comment]
Thanks for your comments. Docker is now started.
However, I'm encountered by another error.

ERROR - nextflow/history.lock (No such file or directory)

Thank you in advance.

**Comment by MaestSi** [comment]
Hi,
the error:
`.command.sh: line 4: qiime: command not found`
suggests me that your Docker installation is not ok yet. Try running without `-resume`, as there is nothing to resume, you're just at the beginning of the pipeline.
Second, remember to mount `/Users` directory, if you haven't already, and remember to always use full file paths.
Best,
SM

**Comment by ObRICa** [comment]
Thanks for your reply.
Even after running without -resume, same error has occurred.
Command error:
  .command.sh: line 4: qiime: command not found

As for the File sharing, I used the full file paths, but it did not solve the problem.

**Comment by MaestSi** [comment]
Is Docker properly configured? I mean, if you run it in the terminal without sudo is it up and running?
SM

**Comment by ObRICa** [comment]
I followed instructions here.
https://docs.docker.com/get-started/02_our_app/

I can see the image of nextflow in Docker, but running it results in failure.
I think there is options to change in the Dockerfile? For example, 
wget https://data.qiime2.org/distro/core/qiime2-2023.5-py38-linux-conda.yml  

It is a unix version on qiime2 (I'm using macOS). Please let me know anything else that I'm missing.

**Comment by MaestSi** [comment]
Hi,
you are not required to re-build the Docker image. I already did it once, and I uploaded it to [DockerHub](https://hub.docker.com/r/maestsi/metontiime). Nextflow will take care of downloading it from there. The only reason why the Dockerfile is there is to show users what is supposed to be in the MetONTIIME image, and how I built it.
All you need is:
- A working [nextflow](https://www.nextflow.io/docs/latest/getstarted.html#installation) installation
- A working [Docker](https://docs.docker.com/desktop/install/mac-install/) (or Singularity) installation. If you are working on Mac, you can install it through Docker Desktop, at [this link](https://docs.docker.com/desktop/install/mac-install/).

Then, when nextflow is available and in path (`nextflow --help` provides the help) and Docker is up and running (`docker --help` provides the help), you can go on with the pipeline.
In particular, remember to mount (i.e. to make accessible to Docker container) the directories in the host OS that need to be accessed for reading/writing data. You can do that by editing line 74 of metontiime2.conf file with something like:
`containerOptions = '--bind /Users/:/Users'`
For example this line will mount /Users directory of your Mac into /Users directory of the container's file system.
Let me know if everything is clear!
Best,
SM

**Comment by ObRICa** [comment]
Thanks for all the suggestions.
I have gone through the nextflow and docker installing again, and now the docker is working (I can see the image " maestsi/metontiime:latest" running).
However, the process still stops with error at importFastq for which I could not figure out what went wrong. I'm showing the error message. Sorry for disturbing you many times, but I feel this is close to the goal. Your help may truly be appreciated.

----------
ERROR ~ Error executing process > 'importFastq'

Caused by:
  Process `importFastq` terminated with an error exit status (1)

Command executed:

  mkdir -p /Users/xxxx/nextflow_MetONTIIME/MetONTIIME/resultsDir/importFastq
  
  fq=$(realpath $(find /Users/xxxx/nextflow_MetONTIIME/MetONTIIME/resultsDir/downsampleFastq/ -maxdepth 1 | grep "\.fastq\.gz"))
  manifestFile=/Users/xxxx/nextflow_MetONTIIME/MetONTIIME/resultsDir/importFastq/manifest.txt
  
  if [ ! -f "$manifestFile" ]; then
  			echo -e sample-id"	"absolute-filepath > $manifestFile;
  mmand output: 	for f in $fq; do
    mpty)       	s=$(echo $(basename $f) | sed 's/\.fastq\.gz//g');
    			echo -e $s"	"$f >> $manifestFile;
  mmand error:  	done
  fi
  
  if [ ! -f /path/to/sample-metadata.tsv ]; then
  /Users/asamizu_macpro/echo -e sample-id"E/MetO"sample-name > /path/to/sample-metadata.tsv;
  			for f in $fq; do
     you can replicate ts=$(echo $(basename $f) | sed 's/\.fastq\.gz//g');
    			echo -e $s"	"$s >> /path/to/sample-metadata.tsv;
  - Check '.nextflow.logdone
  fi
  
  qiime tools import 		--type 'SampleData[SequencesWithQuality]' 		--input-path $manifestFile 	--input-format 'SingleEndFastqManifestPhred33V2' 		--output-path /Users/xxxx/nextflow_MetONTIIME/MetONTIIME/resultsDir/importFastq/sequences.qza
  
  ln -s /Users/xxxx/nextflow_MetONTIIME/MetONTIIME/resultsDir/importFastq/sequences.qza ./sequences.qza

Command exit status:
  1

Command output:
  (empty)

Command error:
  .command.sh: line 16: /path/to/sample-metadata.tsv: No such file or directory

Work dir:
  /Users/xxxx/nextflow_MetONTIIME/MetONTIIME/work/e3/12f0da568b4beda7def7d8a665df98

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Comment by MaestSi** [comment]
Hi, in the metontiime2.conf file (or as a parameter) you should specify a valid path to sampleMetadata file (not /path/to/sample-metadata.tsv).
SM

**Comment by ObRICa** [comment]
I would like to let you know that the entire scripts worked. Thank you very much!

**Comment by MaestSi** [comment]
Great!
Best,
SM
