### ISSUE TITLE
Taxonomy_tsv file

### ISSUE THREAD

**Issue by leakrema** [MaestSi/MetONTIIME#78]
Hi Simone, 

I downloaded a fasta file from NCBI, but when I run TaxonomyTsv_from_fastaNCBI.R script I don't think I get the proper taxonomy file. I don't know if the problem is in ENTREZ_KEY or something else is the issue. Obtained taxonomy_tsv file attached

Cheers!
[dbTaxonomy.zip](https://github.com/MaestSi/MetONTIIME/files/13513374/dbTaxonomy.zip)

**Comment by MaestSi** [comment]
Hi,
I think there may be some problems either with your taxize installation or with the fasta file. I just re-installed taxize from scratch and manually downloaded from NCBI the fasta file corresponding to the first GenBank ID in the file (NG_242156.1).
I ran the script, and it correctly returned:
`NG_242156.1     Eukaryota;Ascomycota;Sordariomycetes;Hypocreales;Stachybotryaceae;Pottera;Pottera beatricis;`
I would suggest to try reproducing this example, with just the first sequence, to check your installation is ok.
SM

**Comment by leakrema** [comment]
Thank you very much for the quick response! I tried it again, but I used my own ENTREZ_KEY and it worked well. 

PS. I did receive a warning that the taxize package was built under R version 4.3.1 (while version 4.3.2 was the correct one for the package), but it worked once I used my Entrez_key

Cheers!

**Comment by MaestSi** [comment]
Great!
Best,
SM
