### ISSUE TITLE
Switching to GreenGenes db

### ISSUE THREAD

**Issue by annegilewski** [MaestSi/MetONTIIME#81]
Hello again!

The pipeline is working like a champ! My chair wants to switch from the NCBI BioProject database to the GreenGenes2 since it was released last year. 

I created the NCBI sequences.fasta and corresponding taxonomy.tsv per your instructions. Now that we want to swap out to GreenGenes, I just wanted to inquire on how to make those adjustments in the .conf script. 

From this site I found information on full sequence .qza files: https://docs.qiime2.org/2023.9/data-resources/#taxonomy-classifiers-for-use-with-q2-feature-classifier and received these files: 2022.10.taxonomy.id.tsv.qza and gg_2022_10_backbone_full_length.nb.qza

However, when I visit the GreenGenes link on your page, I'm sent to this index: https://ftp.microbio.me/greengenes_release/2022.10/

1) I'm unclear which files from this index that I should pull for the script? 
2) I see where I would replace the artifact files in dbSequencesQza and dbTaxonomyQza, but do I need to have the .fasta and .tsv as well? The index didn't provide files in that extension, so I wasn't sure if that something I have to create? 

//Path to database file with sequences in fasta format
	**dbSequencesFasta**="/Volumes/gilewski/ConcatFiles/Test/sequence.fasta"
	//Path to database file with sequence id-to-taxonomy correspondence in tsv format
	**dbTaxonomyTsv**="/Volumes/gilewski/ConcatFiles/Test/dbTaxonomy.tsv"
	//Name of database file with sequences as QIIME2 artifact (qza); if it is already available, it should be put in resultsDir/importDb
	dbSequencesQza="BIOPROJECT33175_sequence.qza"
	//Name of database file with sequence id-to-taxonomy correspondence as QIIME2 artifact (qza); if it is already available, it should be put in resultsDir/importDb
	dbTaxonomyQza="BIOPROJECT33175_taxonomy.qza" 

Many thanks for your help!
Anne

**Comment by MaestSi** [comment]
Hi,
the files on QIIME2 docs point to a Naive-Bayes classifier, which is not what we use with Nanopore reads (we rely on alignment-based classifiers instead).
You should use this [sequences file](https://ftp.microbio.me/greengenes_release/2022.10/2022.10.backbone.full-length.fna.qza) and this [taxonomy file](https://ftp.microbio.me/greengenes_release/2022.10/2022.10.backbone.tax.qza) with MetONTIIME. You may either unzip them, go to data folder and find fasta and tsv files to be used as **dbSequencesFasta** and **dbTaxonomyTsv** files respectively, or you may specify them as **dbSequencesQza** and **dbTaxonomyQza**, but remember in that case to create **resultsDir/importDb** folder and save there the two qza files before running the pipeline. In the latter case, you should also set to false **importDb** process.
Best,
SM

**Comment by annegilewski** [comment]
Gotcha. 

I have my params set up here, and turned 'importdB' to false. However, I'm getting this error when I launch the pipeline: Launching `metontiime2.nf` [happy_gilbert] DSL2 - revision: a578a77f84
Missing `fromPath` parameter

Can I not leave the the paths blank in the params for the fasta and tsv? The files you linked to were qza, not zipped, so I just put them in the artifact lines of the script. 

params{
	//Path to working directory including fastq.gz files
	workDir="/Volumes/gilewski/ConcatFiles/Test"
	//Path to sample metadata tsv file; if it doesn't exist yet, it is created at runtime
	sampleMetadata="/Volumes/gilewski/resultsDir/metadata.tsv"
	//Path to database file with sequences in fasta format
	dbSequencesFasta=""
	//Path to database file with sequence id-to-taxonomy correspondence in tsv format
	dbTaxonomyTsv=""
	//Name of database file with sequences as QIIME2 artifact (qza); if it is already available, it should be put in resultsDir/importDb
	dbSequencesQza="2022.10.seqs.fna.qza"
	//Name of database file with sequence id-to-taxonomy correspondence as QIIME2 artifact (qza); if it is already available, it should be put in resultsDir/importDb
	dbTaxonomyQza="2022.10.taxonomy.asv.tsv.qza"

**Comment by MaestSi** [comment]
Please leave the **dbSequencesFasta** and **dbTaxonomyTsv** set to whatever existing file. They are not going to be used if you set **importDb** to false, but the pipeline will still check they exist.
SM

**Comment by annegilewski** [comment]
Got it! Thank you!

**Comment by annegilewski** [comment]
Sorry, I should have commented to close out on my post. Happy New Year!Anne ***@***.*** Dec 29, 2023, at 15:07, Simone Maestri ***@***.***> wrote:﻿
Please leave the dbSequencesFasta and dbTaxonomyTsv set to whatever existing file. They are not going to be used if you set importDb to false, but the pipeline will still check they exist.
SM

**Comment by MaestSi** [comment]
Happy new year!
SM
