### ISSUE TITLE
Error 137 on Docker

### ISSUE THREAD

**Issue by annegilewski** [MaestSi/MetONTIIME#82]
Hi there!

New year, new problems. I was able to get GreenGenes2 loaded and running. However, when I use Blast or Vsearch I run into a 137 error in Docker at AssignTaxa. Basically as I understand it, the container is running out of memory. 

I went and increased the AssignTaxa CPU/RAM in the script which didn't seem to resolve the issue (this is on a 64GB/4CPU Intel Mac). I increased the resources in Docker itself as well.  We had also adjusted the sensitivity parameters (minQuery, minID, clustID) to help with the percentage of unassigned reads--which shouldn't have affected the container. 

Anyway, I was wondering if Singularity might be a better option here? I'm really stumped as to what is going on. For the record, we were able to run Vsearch/BioProject just fine through the pipeline.  I'm including the error below. I created a token with NextTower to see if I could find out new information, but it seem that Docker runs fine and then just stops. I actually saw it happen today where the container shut down. 

The exit status of the task that caused the workflow execution to fail was: 137

Error executing process > 'assignTaxonomy (1)'

Caused by:
  Process `assignTaxonomy (1)` terminated with an error exit status (137)

Command executed:

  mkdir -p /Volumes/gilewski/resultsDir/assignTaxonomy
  
  	classifier_uc=$(awk '{print toupper($0)'} <<< Vsearch)
  
  	if [ "$classifier_uc" == "BLAST" ]; then
  		qiime feature-classifier makeblastdb 			--i-sequences /Volumes/gilewski/resultsDir/importDb/2022.10.backbone.full-length.fna.qza 			--o-database /Volumes/gilewski/resultsDir/importDb/blastIndexedDb.qza
  
  		qiime feature-classifier classify-consensus-blast 			--i-query /Volumes/gilewski/resultsDir/derepSeq/rep-seqs.qza  			--i-blastdb /Volumes/gilewski/resultsDir/importDb/blastIndexedDb.qza 			--i-reference-taxonomy /Volumes/gilewski/resultsDir/importDb/2022.10.backbone.tax.qza 			--p-num-threads 3 			--p-perc-identity 0.8 			--p-query-cov 0.7 			--p-maxaccepts 3 			--p-min-consensus 0.7 			--o-classification /Volumes/gilewski/resultsDir/assignTaxonomy/taxonomy.qza 			--o-search-results /Volumes/gilewski/resultsDir/assignTaxonomy/search_results.qza
  	elif [ "$classifier_uc" == "VSEARCH" ]; then
  		qiime feature-classifier classify-consensus-vsearch 			--i-query /Volumes/gilewski/resultsDir/derepSeq/rep-seqs.qza  			--i-reference-reads /Volumes/gilewski/resultsDir/importDb/2022.10.backbone.full-length.fna.qza 			--i-reference-taxonomy /Volumes/gilewski/resultsDir/importDb/2022.10.backbone.tax.qza 			--p-perc-identity 0.8 			--p-query-cov 0.7 			--p-maxaccepts 100 			--p-maxrejects 100 			--p-maxhits 3 			--p-min-consensus 0.7 			--p-strand 'both' 			--p-unassignable-label 'Unassigned' 			--p-threads 3 			--o-classification /Volumes/gilewski/resultsDir/assignTaxonomy/taxonomy.qza 			--o-search-results /Volumes/gilewski/resultsDir/assignTaxonomy/search_results.qza
  	else
  		echo "Classifier Vsearch is not supported (choose between Blast and Vsearch)"
  	fi
  
  qiime metadata tabulate 		--m-input-file /Volumes/gilewski/resultsDir/assignTaxonomy/taxonomy.qza 		--o-visualization /Volumes/gilewski/resultsDir/assignTaxonomy/taxonomy.qzv
  
  	qiime taxa filter-table 		--i-table /Volumes/gilewski/resultsDir/derepSeq/table.qza 		--i-taxonomy /Volumes/gilewski/resultsDir/assignTaxonomy/taxonomy.qza 		--p-exclude Unassigned 		--o-filtered-table /Volumes/gilewski/resultsDir/derepSeq/table-no-Unassigned.qza

Command exit status:
  137

Command output:
  (empty)

Command error:
  .command.sh: line 14:    43 Killed                  qiime feature-classifier classify-consensus-vsearch --i-query /Volumes/gilewski/resultsDir/derepSeq/rep-seqs.qza --i-reference-reads /Volumes/gilewski/resultsDir/importDb/2022.10.backbone.full-length.fna.qza --i-reference-taxonomy /Volumes/gilewski/resultsDir/importDb/2022.10.backbone.tax.qza --p-perc-identity 0.8 --p-query-cov 0.7 --p-maxaccepts 100 --p-maxrejects 100 --p-maxhits 3 --p-min-consensus 0.7 --p-strand 'both' --p-unassignable-label 'Unassigned' --p-threads 3 --o-classification /Volumes/gilewski/resultsDir/assignTaxonomy/taxonomy.qza --o-search-results /Volumes/gilewski/resultsDir/assignTaxonomy/search_results.qza

**Comment by MaestSi** [comment]
Hi,
I don't think using Singularity should make any difference compared to Docker. I agree this is an error due to not enough available RAM memory. If you want to use GreenGenes, you could try either reducing the number of reads (process `downsampleFastq = true` and `maxNumReads=10000`, for example) or performing clustering with lower identity (e.g. `clusteringIdentity=0.9`) or using a clustered version og GreenGenes database (e.g. clustered at 97% identity).
SM

**Comment by annegilewski** [comment]
Agreed. I tried with reducing our sensitivity to no avail. For what it's worth, the pipeline works great on a Mac with BioProject/VSearch for 16S MinION reads. BioProject 33175 looks like it has been updated in recent years and we feel confident in the database for now. 

Thanks and we can close this issue. 

All best!
A

**Comment by MaestSi** [comment]
Ok, ciao!
SM
