### ISSUE TITLE
Guppy Warning?

### ISSUE THREAD

**Issue by sekhwal** [MaestSi/MetONTIIME#9]
Import_database.sh has successfully generated sequence_taxonomy.qza and sequence_sequence.qza. Therefore, I run Launch_MinION_mobile_lab.sh <fast5_dir> but it is showing following warning message and not able to generate output files...

-------------------------------------------------------------------
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**********************[guppy/warning] Common::BarcodeTrimmer::CheckTrimLengthValid: Cannot trim more than the size of the FastQ Record sequence, so keeping one base to stop the read being completely empty. Trim length: 169 Sequence length: 144

***[guppy/warning] Common::BarcodeTrimmer::CheckTrimLengthValid: Cannot trim a negative number, so will trim 0, Trim length: -24 Sequence length: 52

********[guppy/warning] Common::BarcodeTrimmer::CheckTrimLengthValid: Cannot trim a negative number, so will trim 0, Trim length: -29 Sequence length: 51

[guppy/warning] Common::BarcodeTrimmer::CheckTrimLengthValid: Cannot trim a negative number, so will trim 0, Trim length: -22 Sequence length: 58

****[guppy/warning] Common::BarcodeTrimmer::CheckTrimLengthValid: Cannot trim more than the size of the FastQ Record sequence, so keeping one base to stop the read being completely empty. Trim length: 160 Sequence length: 135

**************

**Comment by MaestSi** [comment]
Hi,
Are you sure it is not producing output? If that is the case, you should also have some errors besides the warnings. Can you please paste the content of your config file? Moreover, I suggest you to download Guppy v3.4.4 from the ONT website.

**Comment by sekhwal** [comment]
It is generating some files but not all as suggested in README file such as taxa-bar-plots.qzv, taxa-bar-plots-no-Unassigned.qzv etc. Please find attached file for detailed information. 

--------
[nohup.pdf](https://github.com/MaestSi/MetONTIIME/files/4061215/nohup.pdf)
![Picture1](https://user-images.githubusercontent.com/26156590/72377911-32629480-36c5-11ea-8834-a3e927af030d.png)
![Picture3](https://user-images.githubusercontent.com/26156590/72377912-32629480-36c5-11ea-986d-a7e61defbfd4.png)

**Comment by MaestSi** [comment]
It is running, you just have to wait for the job to finish. With 75k reads, it should take about 1 day.

**Comment by sekhwal** [comment]
Ok! However, last time when I run pipeline, there was not any Guppy warning message...Here, it was the message..

----------

Found 24 fastq files.

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Done in 18467 ms.
Demultiplexing finished at Thu Jan  9 20:23:33 2020

Number of basecalled reads: 85256

Creating folder: /home/kumarm/MinION-data/MetONTIIME/fast5_pass_analysis/qc, which is going to include stats about the sequencing run

**Comment by MaestSi** [comment]
You are right, this is due to the fact that recently I removed Porechop for adapters trimming, as it is unsupported since Oct ‘18, and now the adapters trimming is performed by Guppy itself during demultiplexing. Therefore the warnings are now there, but you don’t have to worry about those.

**Comment by sekhwal** [comment]
I suspect, it is running since it is showing same message for long time....Last time it did not take that much time.....Any way I am going to keep it running for a full night...

-------------
Running the MetONTIIME pipeline

Imported /home/kumarm/MinION-data/MetONTIIME/fast5_pass_analysis/analysis/manifest.txt as SingleEndFastqManifestPhred33V2 to sequences.qza
Saved FeatureTable[Frequency] to: table_tmp.qza
Saved FeatureData[Sequence] to: rep-seqs_tmp.qza
Saved FeatureTable[Frequency] to: table.qza
Saved FeatureData[Sequence] to: rep-seqs.qza
Saved Visualization to: demux_summary.qzv
Saved Visualization to: table.qzv
Saved Visualization to: rep-seqs.qzv

**Comment by sekhwal** [comment]
Also, I would like to mention the process that I performed to figure out my previous issue, I am not sure if it is still MetONTIIME_env problem. 

Since pipeline was not able to generate MetONTIIME_env directory and it was installing all files such as seqtk, pycoQC, NanoFilt in /home/kumarm/miniconda3/bin but then I manually created empty directory MetONTIIME_env at /home/kumarm/miniconda3/envs and run ./install.sh. Thus, pipeline was able to generate all necessary files in MetONTIIME_env directory. Subsequently,  I RUN Import_database.sh <"sample_name".fasta>and it was generated sample_name"_sequence.qza and sample_name"_taxonomy.qza.

Do you think it is good?

**Comment by MaestSi** [comment]
Hi,
when you want to check if a job is still running, you can do the following:
`htop -u kumarm`
or
`top -u kumarm`
and you will see if you have a job related to this pipeline that is still running or not. Type `q` to quit top or htop.
Regarding your last observation: in my tests, the `MetONTIIME_env` and `entrez_qiime_env` conda environments were generated simply running **install.sh** and **Import_database.sh** scripts. However, if in your implementation that was not the case, and creating an empy MetONTIIME_env directory solved it, then I think it was a good intuition.
Simone

**Comment by sekhwal** [comment]
I think, there is no any job running at my CPU related the pipeline. The pipeline generated all output files at <fast5_dir>_analysis/analysis with following message (Workflow ended at Wed Jan 15 00:05:13 2020!) in nohup.out file.

I believe it is done!

---------
Imported /home/kumarm/MinION-data/MetONTIIME/fast5_pass_analysis/analysis/manifest.txt as SingleEndFastqManifestPhred33V2 to sequences.qza
Saved FeatureTable[Frequency] to: table_tmp.qza
Saved FeatureData[Sequence] to: rep-seqs_tmp.qza
Saved FeatureTable[Frequency] to: table.qza
Saved FeatureData[Sequence] to: rep-seqs.qza
Saved Visualization to: demux_summary.qzv
Saved Visualization to: table.qzv
Saved Visualization to: rep-seqs.qzv
Saved FeatureData[Taxonomy] to: taxonomy.qza
Saved Visualization to: taxonomy.qzv
Saved Visualization to: taxa-bar-plots.qzv
Saved FeatureTable[Frequency] to: table-no-Unassigned.qza
Saved Visualization to: taxa-bar-plots-no-Unassigned.qzv
Saved FeatureTable[Frequency] to: table_collapsed.qza
Exported table_collapsed.qza as BIOMV210DirFmt to directory .
Saved FeatureTable[RelativeFrequency] to: table_collapsed_relfreq.qza
Saved Visualization to: table_collapsed_relfreq.qzv
Exported table_collapsed_relfreq.qza as BIOMV210DirFmt to directory .
Workflow ended at Wed Jan 15 00:05:13 2020!
Look at the results in directory /home/kumarm/MinION-data/MetONTIIME/fast5_pass_analysis/analysis

**Comment by MaestSi** [comment]
Yes, it is done! Congrats!
Simone

**Comment by sekhwal** [comment]
Thank you for your consistent support! It took several hours though.
--
So, if I do not need diversity and alpha-rarefaction information, I no need to run Evaluate_diversity.sh Right?

**Comment by MaestSi** [comment]
Exactly, you are done. Just have a look at taxa-bar-plots.qzv importing the file [here](https://view.qiime2.org/). You will be able to pick the taxonomic level of interest, from Phylum to Species, and to download the plot or a csv file with taxonomy.
Simone

**Comment by sekhwal** [comment]
Yes! I can see a bar plat of  Phylum to Species. Thank you.

**Comment by MaestSi** [comment]
Perfect, you are welcome.
Simone
