### ISSUE TITLE
Cannot re-open Issue at https://github.com/MaestSi/MetONTIIME/issues/93#issuecomment-1985402041

### ISSUE THREAD

**Issue by richelbilderbeek** [MaestSi/MetONTIIME#95]
Dear MetONTIIME maintainers,

I am unsure what can cause this, but I cannot re-open the Issue at https://github.com/MaestSi/MetONTIIME/issues/93#issuecomment-1985402041 . 

This is the first time I see Issues cannot be reopened. Maybe this is restricted to repo maintainers?

Would be great if the Issue could be re-opened, as the Issue title has not been met yet and/or the Issue has ended with some other conclusion. Thanks!

**Comment by MaestSi** [comment]
I don't know what may be causing this. I saw you recently forked the repository. What about adding all the necessary files for testing to your forked repository? I am not interested in providing further datasets for testing at the moment, but in case other users ask for this, I may consider changing my mind.
SM

**Comment by richelbilderbeek** [comment]
Hi @MaestSi,

Thanks for your reply!

> What about adding all the necessary files for testing to your forked repository?

Well spotted! Yep, that was exactly what I tried to: get a set of files for a minimal test run.

However, I cannot get this to work. Your hints are helpful for a metageneticist, which I am not. I will ask a colleague to help me out: it would be nice if there was a minimal/example set of files to demonstrate this tool with.

> I am not interested in providing further datasets for testing at the moment, but in case other users ask for this, I may consider changing my mind.

Great! I do want to share I know some users that tried MetONTIIME but gave up even after your (again, amazing how you do that!) answer on their Issues. If only there was a minimal/example set of files to demonstrate this tool with :-)

As my user (I am in support) is now helped out, the peace and quiet will return, as I will work on other things again. Keep up the goob job and cheers, Richel
